### ISSUE TITLE
Remove from notification list

### ISSUE THREAD

**Issue by frmeier** [cms-sw/cmssw#11648]
Dear maintainers

As I left CMS per end of September, I kindly request to remove myself from the notification list. According to issue #2394, I'm subscribed to the following list:
* Alignment/CommonAlignment
* Alignment/CommonAlignmentAlgorithm
* Alignment/CommonAlignmentParametrization
* Alignment/CommonAlignmentProducer
* Alignment/MillePedeAlignmentAlgorithm
* Alignment/OfflineValidation
* Alignment/ReferenceTrajectories
* Alignment/SurveyAnalysis
* Alignment/TrackerAlignment
* Alignment/TwoBodyDecay
* MuonAnalysis/MomentumScaleCalibration

Kind regards (and thanks for the good times), Frank

**Comment by davidlt** [comment]
Done

https://github.com/cms-sw/cms-bot/commit/3b9f9c6ca31bc58b7000ae48295bc00863cb91ca

Apologies for the delay.

**Comment by frmeier** [comment]
@davidlt 
I still receive notifications, e.g. just got this one:
https://github.com/cms-sw/cmssw/pull/11956#event-443623638
I checked and see that I do not 'watch' this repo. Any ideas?
