### ISSUE TITLE
SiStripDigitizer (invalid reads), exception: [SiStripThreshold::getData] asking for data for a strip 0 lower then the first stored strip 0

### ISSUE THREAD

**Issue by davidlt** [cms-sw/cmssw#14110]
There are two unit tests failing in DEVEL IBs:
- `runtestRecoLocalCaloHGCalRecProducers` (`RecoLocalCalo/HGCalRecProducers`)
- `runtestSimCalorimetryHGCalSimProducers` (`SimCalorimetry/HGCalSimProducers`)

```
----- Begin Fatal Exception 14-Apr-2016 19:45:45 CEST-----------------------
An exception of category 'CorruptedData' occurred while
   [0] Processing run: 1 lumi: 1 event: 1
   [1] Running path 'digitisation_step'
   [2] Calling event method for module MixingModule/'mix'
Exception Message:
[SiStripThreshold::getData] asking for data for a strip 1 lower then the first stored strip 0
----- End Fatal Exception -------------------------------------------------
```

```
----- Begin Fatal Exception 14-Apr-2016 19:40:33 CEST-----------------------
An exception of category 'CorruptedData' occurred while
   [0] Processing run: 1 lumi: 1 event: 1
   [1] Running path 'digitisation_step'
   [2] Calling event method for module MixingModule/'mix'
Exception Message:
[SiStripThreshold::getData] asking for data for a strip 2 lower then the first stored strip 4
----- End Fatal Exception -------------------------------------------------
```

jemalloc is newer in DEVEL IB, thus first thought that something most likely depends on random garbage in memory. Quick valgrind run shows that we have invalid reads from the following libs:
- libGeometryHcalCommonData.so
- pluginSimTrackerSiStripDigitizerPlugins.so
- libSimTrackerSiStripDigitizer.so
- libL1TriggerL1TCalorimeter.so

Then recompiled packages on DEVEL and normal IB with debug information and repeated valgrind run, both showed the same results before failing.

```
Begin processing the 1st record. Run 1, Event 1, LumiSection 1 at 16-Apr-2016 09:26:52.346 CEST
TrackerParametersESModule::produce(const PTrackerParametersRcd& iRecord)
==25404== Invalid read of size 4
==25404==    at 0x20787A2D: HcalDDDRecConstants::getHCID(int, int, int, int, int) const (HcalDDDRecConstants.cc:143)
==25404==    by 0x2DD7E433: HcalHitRelabeller::relabel(unsigned int) const (in /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-14-2300/lib/slc6_amd64_gcc530/libSimCalorimetryHcalSimProducers.so)
==25404==    by 0x2DD7E55D: HcalHitRelabeller::process(std::vector<PCaloHit, std::allocator<PCaloHit> >&) (in /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-14-2300/lib/slc6_amd64_gcc530/libSimCalorimetryHcalSimProducers.so)
==25404==    by 0x2DD8A45F: HcalDigitizer::accumulateCaloHits(edm::Handle<std::vector<PCaloHit, std::allocator<PCaloHit> > > const&, edm::Handle<std::vector<PCaloHit, std::allocator<PCaloHit> > > const&, int, CLHEP::HepRandomEngine*, HcalTopology const*) (in /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-14-2300/lib/slc6_amd64_gcc530/libSimCalorimetryHcalSimProducers.so)
==25404==    by 0x2DD8B15C: HcalDigitizer::accumulate(edm::Event const&, edm::EventSetup const&, CLHEP::HepRandomEngine*) (in /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-14-2300/lib/slc6_amd64_gcc530/libSimCalorimetryHcalSimProducers.so)
==25404==    by 0x2DD7D673: HcalDigiProducer::accumulate(edm::Event const&, edm::EventSetup const&) (in /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-14-2300/lib/slc6_amd64_gcc530/libSimCalorimetryHcalSimProducers.so)
==25404==    by 0x2DCF310A: edm::MixingModule::accumulateEvent(edm::Event const&, edm::EventSetup const&) (in /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-14-2300/lib/slc6_amd64_gcc530/pluginSimGeneralMixingModulePlugins.so)
==25404==    by 0x2DCF312E: edm::MixingModule::addSignals(edm::Event const&, edm::EventSetup const&) (in /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-14-2300/lib/slc6_amd64_gcc530/pluginSimGeneralMixingModulePlugins.so)
==25404==    by 0x2CD37665: edm::BMixingModule::produce(edm::Event&, edm::EventSetup const&) (in /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-14-2300/lib/slc6_amd64_gcc530/libMixingBase.so)
==25404==    by 0x4BFB431: edm::stream::EDProducerAdaptorBase::doEvent(edm::EventPrincipal const&, edm::EventSetup const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) (in /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-14-2300/lib/slc6_amd64_gcc530/libFWCoreFramework.so)
==25404==    by 0x4BD272E: edm::WorkerT<edm::stream::EDProducerAdaptorBase>::implDo(edm::EventPrincipal const&, edm::EventSetup const&, edm::ModuleCallingContext const*) (in /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-14-2300/lib/slc6_amd64_gcc530/libFWCoreFramework.so)
==25404==    by 0x4B22A9B: decltype ({parm#1}()) edm::convertException::wrap<bool edm::Worker::doWork<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}>(bool edm::Worker::doWork<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}) (in /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-14-2300/lib/slc6_amd64_gcc530/libFWCoreFramework.so)
==25404==  Address 0x5e39fd10 is 0 bytes after a block of size 64 alloc'd
==25404==    at 0x4028108: operator new(unsigned long) (in /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/external/valgrind/3.11.0/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==25404==    by 0x3456569C: std::_Rb_tree_iterator<std::pair<unsigned int const, std::vector<double, std::allocator<double> > > > std::_Rb_tree<unsigned int, std::pair<unsigned int const, std::vector<double, std::allocator<double> > >, std::_Select1st<std::pair<unsigned int const, std::vector<double, std::allocator<double> > > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::vector<double, std::allocator<double> > > > >::_M_emplace_hint_unique<std::piecewise_construct_t const&, std::tuple<unsigned int const&>, std::tuple<> >(std::_Rb_tree_const_iterator<std::pair<unsigned int const, std::vector<double, std::allocator<double> > > >, std::piecewise_construct_t const&, std::tuple<unsigned int const&>&&, std::tuple<>&&) (in /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-14-2300/lib/slc6_amd64_gcc530/pluginSimMuonRPCDigitizer.so)
==25404==    by 0x3455FF6A: RPCSimSetUp::setRPCSetUp(std::vector<RPCStripNoises::NoiseItem, std::allocator<RPCStripNoises::NoiseItem> > const&, std::vector<RPCClusterSize::ClusterSizeItem, std::allocator<RPCClusterSize::ClusterSizeItem> > const&) (in /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-14-2300/lib/slc6_amd64_gcc530/pluginSimMuonRPCDigitizer.so)
==25404==    by 0x3456E84A: RPCDigiProducer::beginRun(edm::Run const&, edm::EventSetup const&) (in /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-14-2300/lib/slc6_amd64_gcc530/pluginSimMuonRPCDigitizer.so)
==25404==    by 0x4BFC74A: edm::stream::ProducingModuleAdaptorBase<edm::stream::EDProducerBase>::doStreamBeginRun(edm::StreamID, edm::RunPrincipal const&, edm::EventSetup const&, edm::ModuleCallingContext const*) (in /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-14-2300/lib/slc6_amd64_gcc530/libFWCoreFramework.so)
==25404==    by 0x4BD036C: edm::WorkerT<edm::stream::EDProducerAdaptorBase>::implDoStreamBegin(edm::StreamID, edm::RunPrincipal const&, edm::EventSetup const&, edm::ModuleCallingContext const*) (in /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-14-2300/lib/slc6_amd64_gcc530/libFWCoreFramework.so)
==25404==    by 0x4B28921: decltype ({parm#1}()) edm::convertException::wrap<bool edm::Worker::doWork<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}>(bool edm::Worker::doWork<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}) (in /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-14-2300/lib/slc6_amd64_gcc530/libFWCoreFramework.so)
==25404==    by 0x4B28B40: bool edm::Worker::doWork<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)1>::Context const*) (in /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-14-2300/lib/slc6_amd64_gcc530/libFWCoreFramework.so)
==25404==    by 0x4B28CE9: decltype ({parm#1}()) edm::convertException::wrap<void edm::Path::processOneOccurrence<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID const&, edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}>(void edm::Path::processOneOccurrence<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID const&, edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}) (in /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-14-2300/lib/slc6_amd64_gcc530/libFWCoreFramework.so)
==25404==    by 0x4B28EB6: void edm::Path::processOneOccurrence<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID const&, edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)1>::Context const*) (in /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-14-2300/lib/slc6_amd64_gcc530/libFWCoreFramework.so)
==25404==    by 0x4B2915D: decltype ({parm#1}()) edm::convertException::wrap<void edm::StreamSchedule::processOneStream<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)1>::MyPrincipal&, edm::EventSetup const&, bool)::{lambda()#1}>(void edm::StreamSchedule::processOneStream<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)1>::MyPrincipal&, edm::EventSetup const&, bool)::{lambda()#1}) (in /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-14-2300/lib/slc6_amd64_gcc530/libFWCoreFramework.so)
==25404==    by 0x4B297A6: void edm::StreamSchedule::processOneStream<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)1>::MyPrincipal&, edm::EventSetup const&, bool) (in /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-14-2300/lib/slc6_amd64_gcc530/libFWCoreFramework.so)
```

```
==25404== Invalid read of size 4
==25404==    at 0x30B39C76: SiStripApvGain::getStripGain(unsigned short, std::pair<__gnu_cxx::__normal_iterator<float const*, std::vector<float, std::allocator<float> > >, __gnu_cxx::__normal_iterator<float const*, std::vector<float, std::allocator<float> > > > const&) (SiStripApvGain.h:76)
==25404==    by 0x30B39CC9: SiStripGain::getStripGain(unsigned short const&, std::pair<__gnu_cxx::__normal_iterator<float const*, std::vector<float, std::allocator<float> > >, __gnu_cxx::__normal_iterator<float const*, std::vector<float, std::allocator<float> > > > const&) (SiStripGain.h:68)
==25404==    by 0x30B45F96: SiStripDigitizerAlgorithm::digitize(edm::DetSet<SiStripDigi>&, edm::DetSet<SiStripRawDigi>&, edm::DetSet<StripDigiSimLink>&, StripGeomDetUnit const*, edm::ESHandle<SiStripGain>&, edm::ESHandle<SiStripThreshold>&, edm::ESHandle<SiStripNoises>&, edm::ESHandle<SiStripPedestals>&, CLHEP::HepRandomEngine*) (SiStripDigitizerAlgorithm.cc:270)
==25404==    by 0x30B5AD2E: SiStripDigitizer::finalizeEvent(edm::Event&, edm::EventSetup const&) (SiStripDigitizer.cc:241)
==25404==    by 0x2DCF2F7A: edm::MixingModule::finalizeEvent(edm::Event&, edm::EventSetup const&) (in /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-14-2300/lib/slc6_amd64_gcc530/pluginSimGeneralMixingModulePlugins.so)
==25404==    by 0x2CD3769A: edm::BMixingModule::produce(edm::Event&, edm::EventSetup const&) (in /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-14-2300/lib/slc6_amd64_gcc530/libMixingBase.so)
==25404==    by 0x4BFB431: edm::stream::EDProducerAdaptorBase::doEvent(edm::EventPrincipal const&, edm::EventSetup const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) (in /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-14-2300/lib/slc6_amd64_gcc530/libFWCoreFramework.so)
==25404==    by 0x4BD272E: edm::WorkerT<edm::stream::EDProducerAdaptorBase>::implDo(edm::EventPrincipal const&, edm::EventSetup const&, edm::ModuleCallingContext const*) (in /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-14-2300/lib/slc6_amd64_gcc530/libFWCoreFramework.so)
==25404==    by 0x4B22A9B: decltype ({parm#1}()) edm::convertException::wrap<bool edm::Worker::doWork<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}>(bool edm::Worker::doWork<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}) (in /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-14-2300/lib/slc6_amd64_gcc530/libFWCoreFramework.so)
==25404==    by 0x4B23534: bool edm::Worker::doWork<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) (in /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-14-2300/lib/slc6_amd64_gcc530/libFWCoreFramework.so)
==25404==    by 0x4B2429D: decltype ({parm#1}()) edm::convertException::wrap<void edm::Path::processOneOccurrence<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}>(void edm::Path::processOneOccurrence<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}) (in /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-14-2300/lib/slc6_amd64_gcc530/libFWCoreFramework.so)
==25404==    by 0x4B24551: void edm::Path::processOneOccurrence<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) (in /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-14-2300/lib/slc6_amd64_gcc530/libFWCoreFramework.so)
==25404==  Address 0xd0a136c0 is 0 bytes after a block of size 291,136 alloc'd
==25404==    at 0x4028108: operator new(unsigned long) (in /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/external/valgrind/3.11.0/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==25404==    by 0x204071EB: std::vector<float, std::allocator<float> >::reserve(unsigned long) (in /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-14-2300/lib/slc6_amd64_gcc530/libCondFormatsGeometryObjects.so)
==25404==    by 0x204116C2: boost::archive::detail::iserializer<eos::portable_iarchive, std::vector<float, std::allocator<float> > >::load_object_data(boost::archive::detail::basic_iarchive&, void*, unsigned int) const (in /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-14-2300/lib/slc6_amd64_gcc530/libCondFormatsGeometryObjects.so)
==25404==    by 0x20323F86: boost::archive::detail::basic_iarchive::load_object(void*, boost::archive::detail::basic_iserializer const&) (in /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/external/boost/1.57.0-ikhhed/lib/libboost_serialization.so.1.57.0)
==25404==    by 0x26CE0B50: void boost::archive::detail::load_non_pointer_type<eos::portable_iarchive>::load_standard::invoke<std::vector<float, std::allocator<float> > >(eos::portable_iarchive&, std::vector<float, std::allocator<float> > const&) (iserializer.hpp:410)
==25404==    by 0x26CDF1EA: void boost::archive::detail::load_non_pointer_type<eos::portable_iarchive>::load_conditional::invoke<std::vector<float, std::allocator<float> > >(eos::portable_iarchive&, std::vector<float, std::allocator<float> >&) (iserializer.hpp:423)
==25404==    by 0x26CDC872: void boost::archive::detail::load_non_pointer_type<eos::portable_iarchive>::invoke<std::vector<float, std::allocator<float> > >(eos::portable_iarchive&, std::vector<float, std::allocator<float> >&) (iserializer.hpp:462)
==25404==    by 0x26CD7BAA: void boost::archive::load<eos::portable_iarchive, std::vector<float, std::allocator<float> > >(eos::portable_iarchive&, std::vector<float, std::allocator<float> >&) (iserializer.hpp:618)
==25404==    by 0x26CD2988: void boost::archive::detail::common_iarchive<eos::portable_iarchive>::load_override<std::vector<float, std::allocator<float> > >(std::vector<float, std::allocator<float> >&, int) (common_iarchive.hpp:66)
==25404==    by 0x26CCEC7E: void boost::archive::basic_binary_iarchive<eos::portable_iarchive>::load_override<std::vector<float, std::allocator<float> > >(std::vector<float, std::allocator<float> >&, int) (basic_binary_iarchive.hpp:76)
==25404==    by 0x26CCB416: eos::portable_iarchive& boost::archive::detail::interface_iarchive<eos::portable_iarchive>::operator>><std::vector<float, std::allocator<float> > >(std::vector<float, std::allocator<float> >&) (interface_iarchive.hpp:60)
==25404==    by 0x26CC96E6: void boost::serialization::nvp<std::vector<float, std::allocator<float> > >::load<eos::portable_iarchive>(eos::portable_iarchive&, unsigned int) (nvp.hpp:83)
```

```
==25404== Invalid read of size 2
==25404==    at 0x26C4FC98: SiStripThreshold::Data::getFirstStrip() const (SiStripThreshold.h:61)
==25404==    by 0x26C4EEF5: SiStripThreshold::getData(unsigned short const&, std::pair<__gnu_cxx::__normal_iterator<SiStripThreshold::Data const*, std::vector<SiStripThreshold::Data, std::allocator<SiStripThreshold::Data> > >, __gnu_cxx::__normal_iterator<SiStripThreshold::Data const*, std::vector<SiStripThreshold::Data, std::allocator<SiStripThreshold::Data> > > > const&) const (SiStripThreshold.cc:76)
==25404==    by 0x30BE9EA9: SiStripFedZeroSuppression::suppress(std::vector<SiStripDigi, std::allocator<SiStripDigi> > const&, std::vector<SiStripDigi, std::allocator<SiStripDigi> >&, unsigned int const&, edm::ESHandle<SiStripNoises>&, edm::ESHandle<SiStripThreshold>&) (in /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-14-2300/lib/slc6_amd64_gcc530/libRecoLocalTrackerSiStripZeroSuppression.so)
==25404==    by 0x30B46252: SiStripDigitizerAlgorithm::digitize(edm::DetSet<SiStripDigi>&, edm::DetSet<SiStripRawDigi>&, edm::DetSet<StripDigiSimLink>&, StripGeomDetUnit const*, edm::ESHandle<SiStripGain>&, edm::ESHandle<SiStripThreshold>&, edm::ESHandle<SiStripNoises>&, edm::ESHandle<SiStripPedestals>&, CLHEP::HepRandomEngine*) (SiStripDigitizerAlgorithm.cc:292)
==25404==    by 0x30B5AD2E: SiStripDigitizer::finalizeEvent(edm::Event&, edm::EventSetup const&) (SiStripDigitizer.cc:241)
==25404==    by 0x2DCF2F7A: edm::MixingModule::finalizeEvent(edm::Event&, edm::EventSetup const&) (in /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-14-2300/lib/slc6_amd64_gcc530/pluginSimGeneralMixingModulePlugins.so)
==25404==    by 0x2CD3769A: edm::BMixingModule::produce(edm::Event&, edm::EventSetup const&) (in /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-14-2300/lib/slc6_amd64_gcc530/libMixingBase.so)
==25404==    by 0x4BFB431: edm::stream::EDProducerAdaptorBase::doEvent(edm::EventPrincipal const&, edm::EventSetup const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) (in /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-14-2300/lib/slc6_amd64_gcc530/libFWCoreFramework.so)
==25404==    by 0x4BD272E: edm::WorkerT<edm::stream::EDProducerAdaptorBase>::implDo(edm::EventPrincipal const&, edm::EventSetup const&, edm::ModuleCallingContext const*) (in /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-14-2300/lib/slc6_amd64_gcc530/libFWCoreFramework.so)
==25404==    by 0x4B22A9B: decltype ({parm#1}()) edm::convertException::wrap<bool edm::Worker::doWork<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}>(bool edm::Worker::doWork<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}) (in /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-14-2300/lib/slc6_amd64_gcc530/libFWCoreFramework.so)
==25404==    by 0x4B23534: bool edm::Worker::doWork<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) (in /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-14-2300/lib/slc6_amd64_gcc530/libFWCoreFramework.so)
==25404==    by 0x4B2429D: decltype ({parm#1}()) edm::convertException::wrap<void edm::Path::processOneOccurrence<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}>(void edm::Path::processOneOccurrence<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}) (in /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-14-2300/lib/slc6_amd64_gcc530/libFWCoreFramework.so)
==25404==  Address 0xd0abcd20 is 0 bytes after a block of size 60,592 alloc'd
==25404==    at 0x4028108: operator new(unsigned long) (in /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/external/valgrind/3.11.0/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==25404==    by 0x26C53FEB: __gnu_cxx::new_allocator<SiStripThreshold::Data>::allocate(unsigned long, void const*) (new_allocator.h:104)
==25404==    by 0x26C52E6C: std::allocator_traits<std::allocator<SiStripThreshold::Data> >::allocate(std::allocator<SiStripThreshold::Data>&, unsigned long) (alloc_traits.h:360)
==25404==    by 0x26C51DDF: std::_Vector_base<SiStripThreshold::Data, std::allocator<SiStripThreshold::Data> >::_M_allocate(unsigned long) (stl_vector.h:170)
==25404==    by 0x26CDBB19: SiStripThreshold::Data* std::vector<SiStripThreshold::Data, std::allocator<SiStripThreshold::Data> >::_M_allocate_and_copy<std::move_iterator<SiStripThreshold::Data*> >(unsigned long, std::move_iterator<SiStripThreshold::Data*>, std::move_iterator<SiStripThreshold::Data*>) (stl_vector.h:1224)
==25404==    by 0x26CD697C: std::vector<SiStripThreshold::Data, std::allocator<SiStripThreshold::Data> >::reserve(unsigned long) (vector.tcc:75)
==25404==    by 0x26CD1BC4: boost::serialization::stl::reserve_imp<std::vector<SiStripThreshold::Data, std::allocator<SiStripThreshold::Data> > >::operator()(std::vector<SiStripThreshold::Data, std::allocator<SiStripThreshold::Data> >&, unsigned long) const (collections_load_imp.hpp:126)
==25404==    by 0x26CF57A7: void boost::serialization::stl::load_collection<eos::portable_iarchive, std::vector<SiStripThreshold::Data, std::allocator<SiStripThreshold::Data> >, boost::serialization::stl::archive_input_seq<eos::portable_iarchive, std::vector<SiStripThreshold::Data, std::allocator<SiStripThreshold::Data> > >, boost::serialization::stl::reserve_imp<std::vector<SiStripThreshold::Data, std::allocator<SiStripThreshold::Data> > > >(eos::portable_iarchive&, std::vector<SiStripThreshold::Data, std::allocator<SiStripThreshold::Data> >&) (collections_load_imp.hpp:153)
==25404==    by 0x26CF3821: void boost::serialization::load<eos::portable_iarchive, SiStripThreshold::Data, std::allocator<SiStripThreshold::Data> >(eos::portable_iarchive&, std::vector<SiStripThreshold::Data, std::allocator<SiStripThreshold::Data> >&, unsigned int, mpl_::bool_<false>) (vector.hpp:73)
==25404==    by 0x26CF17C7: void boost::serialization::load<eos::portable_iarchive, SiStripThreshold::Data, std::allocator<SiStripThreshold::Data> >(eos::portable_iarchive&, std::vector<SiStripThreshold::Data, std::allocator<SiStripThreshold::Data> >&, unsigned int) (vector.hpp:148)
==25404==    by 0x26CEF2A2: boost::serialization::free_loader<eos::portable_iarchive, std::vector<SiStripThreshold::Data, std::allocator<SiStripThreshold::Data> > >::invoke(eos::portable_iarchive&, std::vector<SiStripThreshold::Data, std::allocator<SiStripThreshold::Data> >&, unsigned int) (split_free.hpp:58)
==25404==    by 0x26CED1B8: void boost::serialization::split_free<eos::portable_iarchive, std::vector<SiStripThreshold::Data, std::allocator<SiStripThreshold::Data> > >(eos::portable_iarchive&, std::vector<SiStripThreshold::Data, std::allocator<SiStripThreshold::Data> >&, unsigned int) (split_free.hpp:74)
==25404==
```

Seems to be two packages involved:
- `Geometry/HcalCommonData`
- `CondFormats/SiStripObjects`

Maybe these are out-of-bounds reads? Have not investigated.

**Comment by davidlt** [comment]
@civanch @mdhildreth @ianna @ggovi

**Comment by davidlt** [comment]
Is anyone looking into these?

**Comment by civanch** [comment]
@bsunanda, @kpedro88, @lgray - one of the issues is in libGeometryHcalCommonData.so
Can you , please, have a look

**Comment by civanch** [comment]
@boudoul , who now may be responsible for pluginSimTrackerSiStripDigitizerPlugins.so and libSimTrackerSiStripDigitizer.so ? (@mdhildreth or me can have a look but better if an expert do).

**Comment by boudoul** [comment]
hi , could someone give me a recipe how to run the unit tests which are crashing in this DEVEL  IB ? I would need to reproduce ... thanks

**Comment by davidlt** [comment]
```
cmsRun RecoLocalCalo/HGCalRecProducers/test/testHGCalRecoLocal_cfg.py
```

**Comment by boudoul** [comment]
OK , I took a look, an even if usually I'm happy to help, here I'm a bit reluctant ; This unit test is based on scenario which is mixing phase2 hgcal, phase1 pixel, run2 outer tracker, other run2 whatever stuff using on top if this the run2 era and phase2 customize...... 
So in short a mix of everything and clearly not something (at least the Tracker) is supporting .. Maybe one should ask the original author of this cfg.py (I assume to test the hgcal stuff)  to clean a bit the configuration ?... Happy to help if problems remains afterwards.

**Comment by civanch** [comment]
@kpedro88 , who did this cfg.py?

**Comment by kpedro88** [comment]
@civanch - definitely not me... @lgray?

**Comment by civanch** [comment]
@lgray, likely it is your development, can you clarify?

**Comment by lgray** [comment]
Hi, iirc this is fixed in one of the PRs that just got merged.
If not, it's pretty straightforward to switch to the phase 2 tracker +
HGCal geometries that will be in place in the next IBs.

-L

**Comment by davidlt** [comment]
Well, then I suggest to wait for next 1 or 2 IBs and see if it's resolved.

**Comment by davidlt** [comment]
I still see the same failure in `RecoLocalCalo/HGCalRecProducers` in the latest DEVEL IB, `CMSSW_8_1_DEVEL_X_2016-04-20-2300`.

**Comment by lgray** [comment]
Working on it.

**Comment by bsunanda** [comment]
I believe this is the python file which is to be updated for customizing to PhaseI detector for tracker and Phase2 for everything else
________________________________

**Comment by lgray** [comment]
Hi, if I try to use the Phase2 era and LReco geometry I get the following exception:
```
----- Begin Fatal Exception 21-Apr-2016 12:06:20 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing run: 1 lumi: 1 event: 1
   [1] Running path 'digitisation_step'
   [2] Calling event method for module MixingModule/'mix'
Exception Message:
Principal::getByLabel: Found zero products matching all criteria
Looking for type: std::vector<PSimHit>
Looking for module label: g4SimHits
Looking for productInstanceName: TrackerHitsTIBLowTof

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
```

Any hints? Thanks!

**Comment by lgray** [comment]
OK - found the customize thanks to @kpedro88 Submitting a PR.

**Comment by lgray** [comment]
Fixed in https://github.com/cms-sw/cmssw/pull/14180

**Comment by Dr15Jones** [comment]
@davidlt @smuzaffar can this be closed now?

**Comment by smuzaffar** [comment]
We still have one of these unit tests failing in DEVEL IBs
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc530/CMSSW_8_1_DEVEL_X_2016-05-06-1100/unitTestLogs/SimCalorimetry/HGCalSimProducers

**Comment by lgray** [comment]
OK - I'll fix it up.
