### ISSUE TITLE
edmEventUtil in 810pre15

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmssw#16444]
any ideas?

[dlange@lxplus051 ~/CMSSW_8_1_0_pre15]$ edmFileUtil -v /store/relval/CMSSW_8_1_0_pre15/RelValMinBias_13/GEN-SIM/81X_upgrade2023_realistic_v3_2023D3Timing13TeV-v1/10000/144CC553-5A99-E611-B38B-0CC47A7C3604.root
/store/relval/CMSSW_8_1_0_pre15/RelValMinBias_13/GEN-SIM/81X_upgrade2023_realistic_v3_2023D3Timing13TeV-v1/10000/144CC553-5A99-E611-B38B-0CC47A7C3604.root
ECU:: Opened root://eoscms.cern.ch//eos/cms/store/relval/CMSSW_8_1_0_pre15/RelValMinBias_13/GEN-SIM/81X_upgrade2023_realistic_v3_2023D3Timing13TeV-v1/10000/144CC553-5A99-E611-B38B-0CC47A7C3604.root
ECU:: Collection not autorecovered. Continuing
ECU:: Found Tree MetaData
ECU:: Found Tree Events
ECU:: Found all expected trees
/store/relval/CMSSW_8_1_0_pre15/RelValMinBias_13/GEN-SIM/81X_upgrade2023_realistic_v3_2023D3Timing13TeV-v1/10000/144CC553-5A99-E611-B38B-0CC47A7C3604.root (1 runs, 143 lumis, 7150 events, 2265172564 bytes)

 *** Break *** segmentation violation
Segmentation fault

**Comment by davidlange6** [comment]
assign core

**Comment by Dr15Jones** [comment]
I ran the debugger on the job and get
```
#0  0x0000003fef40aa4a in pthread_rwlock_rdlock () from /lib64/libpthread.so.0
#1  0x00007fffeaf63bc0 in XrdSysRWLock::ReadLock (this=0x8)
    at /build/cmsbuild/auto-builds/CMSSW_8_1_0_pre13-slc6_amd64_gcc530/build/CMSSW_8_1_0_pre13-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.4.1/xrootd-4.4.1/src/./XrdSys/XrdSysPthread.hh:237
#2  XrdSysRWLockHelper::XrdSysRWLockHelper (rd=true, l=..., this=<synthetic pointer>)
    at /build/cmsbuild/auto-builds/CMSSW_8_1_0_pre13-slc6_amd64_gcc530/build/CMSSW_8_1_0_pre13-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.4.1/xrootd-4.4.1/src/./XrdSys/XrdSysPthread.hh:284
#3  XrdCl::Env::GetInt (this=this@entry=0x0, key="MetalinkProcessing", value=@0x7fffffff480c: 1)
    at /build/cmsbuild/auto-builds/CMSSW_8_1_0_pre13-slc6_amd64_gcc530/build/CMSSW_8_1_0_pre13-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.4.1/xrootd-4.4.1/src/XrdCl/XrdClEnv.cc:89
#4  0x00007fffeaf7491c in XrdCl::URL::IsMetalink (this=0x303bf70)
    at /build/cmsbuild/auto-builds/CMSSW_8_1_0_pre13-slc6_amd64_gcc530/build/CMSSW_8_1_0_pre13-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.4.1/xrootd-4.4.1/src/XrdCl/XrdClURL.cc:373
#5  0x00007fffeafb78eb in XrdCl::FileStateHandler::~FileStateHandler (this=0x31e9480, __in_chrg=<optimized out>)
    at /build/cmsbuild/auto-builds/CMSSW_8_1_0_pre13-slc6_amd64_gcc530/build/CMSSW_8_1_0_pre13-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.4.1/xrootd-4.4.1/src/XrdCl/XrdClFileStateHandler.cc:393
#6  0x00007fffeafb54d3 in XrdCl::File::~File (this=0x3115df0, __in_chrg=<optimized out>)
    at /build/cmsbuild/auto-builds/CMSSW_8_1_0_pre13-slc6_amd64_gcc530/build/CMSSW_8_1_0_pre13-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.4.1/xrootd-4.4.1/src/XrdCl/XrdClFile.cc:71
#7  0x00007fffeafb5581 in XrdCl::File::~File (this=0x3115df0, __in_chrg=<optimized out>)
    at /build/cmsbuild/auto-builds/CMSSW_8_1_0_pre13-slc6_amd64_gcc530/build/CMSSW_8_1_0_pre13-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.4.1/xrootd-4.4.1/src/XrdCl/XrdClFile.cc:73
#8  0x00007fffeb164a98 in TNetXNGFile::~TNetXNGFile() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc530/lcg/root/6.06.08-giojec/lib/libNetxNG.so
#9  0x00007fffeb164d99 in TNetXNGFile::~TNetXNGFile() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc530/lcg/root/6.06.08-giojec/lib/libNetxNG.so
#10 0x00007ffff6c07c2d in TList::Delete(char const*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_0_pre15/external/slc6_amd64_gcc530/lib/libCore.so
#11 0x00007ffff6afe315 in TROOT::~TROOT() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_0_pre15/external/slc6_amd64_gcc530/lib/libCore.so
#12 0x0000003feec35ae2 in exit () from /lib64/libc.so.6
#13 0x0000003feec1ed24 in __libc_start_main () from /lib64/libc.so.6
#14 0x000000000040bdc9 in _start ()
```
So it looks like an end of job problem related to xrootd.

**Comment by Dr15Jones** [comment]
@bbockelm @pcanal ideas?

**Comment by Dr15Jones** [comment]
The problem is the delete order of two singletons: `TROOT` and `XrdCl::DefaultEnv`. Using the debugger I found that `XrdCl::DefaultEnv` is destroyed first. Then when `TROOT` is being destroyed, it is deleting `TNetXNGFile` which in turn indirectly calls `XrdCl::DefaultEnv` and gets back a pointer to a destroyed object.

In this particular case I believe we can avoid the problem by deleting the `TFile` ourselves (since `edmFileUtil` fails to delete the object once it is done with it).

**Comment by Dr15Jones** [comment]
Fixed by #16447

**Comment by Dr15Jones** [comment]
+1

**Comment by gpetruc** [comment]
edmFileUtil seems to crash on a xrootd url also in `CMSSW_8_0_24_patch1`
and, I tried cherry-picking ed1816e40e8a0e21972b3cb68975747b059811a2 but it doesn't solve it.

**Comment by wddgit** [comment]
@smuzaffar There is an issue on the XRootD github site with a similar sounding problem and an almost identical stack trace. It references a commit that is supposed to fix the problem. I do not know how to tell whether the version of XROOTD we use has the bug fix. Can you check this or tell me how I can check it?

https://github.com/xrootd/xrootd/issues/433

https://github.com/xrootd/xrootd/commit/7bfa28435a70b71257e0defa239ff963f6e0fc39

**Comment by smuzaffar** [comment]
@wddgit , this was picked in 90X IBs only https://github.com/cms-externals/xrootd/commits/cms/v4.5.0 and is part of CMSSW_9_0_0_pre1. 
@davidlange6 , now that we have validated 900pre1, should we back port xrootd to 75X and above?

**Comment by wddgit** [comment]
I just checked and can confirm that the edmFileUtil bug does not occur in 9_0_X.
Also according to the xrootd issue the bug entered between xrootd versions 4.3.0
and 4.4.0.
