### ISSUE TITLE
LogError in HLTPrescaleProvider used by PATTriggerProducer:patTrigger: Error in determining L1T prescale

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#19802]
this can be seen in workflow 136.78 step3:

```
%MSG-e HLTPrescaleProvider:  PATTriggerProducer:patTrigger  18-Jul-2017 18:52:46 CEST Run: 297227 Event: 32100
 Error in determining L1T prescale for HLT path: 'HLT_ZeroBias_FirstCollisionInTrain_v2' has multiple L1TSeed modules, 2, with L1T seeds: 'L1_FirstCollisionInTrain' * 'NOT L1_FirstCollisionInOrbit'. (Note: at most one L1TSeed module is allowed for a proper determination of the L1T prescale!)
%MSG-e HLTPrescaleProvider:  PATTriggerProducer:patTrigger  18-Jul-2017 18:52:46 CEST Run: 297227 Event: 32100
 Error in determining L1T prescale for HLT path: 'HLT_ZeroBias_LastCollisionInTrain_v1' has multiple L1TSeed modules, 2, with L1T seeds: 'L1_FirstCollisionInTrain' * 'L1_LastCollisionInTrain'. (Note: at most one L1TSeed module is allowed for a proper determination of the L1T prescale!)

```

@Martin-Grunewald @fwyzard @gpetruc @arizzi

**Comment by slava77** [comment]
assign hlt,reconstruction

**Comment by Martin-Grunewald** [comment]
Hi - indeed I see this, eg, in 93X.

These messages are limited to at most 5 per instance of the HLTPrescaleProvider.

One of the two paths, namely HLT_ZeroBias_LastCollisionInTrain, is fixed with the new HLT menu integrated in 93X yesterday, which avoids two HLTL1T seed modules in the path. 

I need to check why this construst was used by the remaining trigger HLT_ZeroBias_FirstCollisionInTrain.

**Comment by Martin-Grunewald** [comment]
The remaining trigger is fixed and will become available with HLT menu V2.1.

**Comment by slava77** [comment]
@Martin-Grunewald 
I notice that the "Error in determining L1T prescale" error is still showing up even in 2018 data processing.
e.g. in 10_3_0_pre5 in wf 136.85 Run2018A EGamma PD

```
%MSG-e HLTPrescaleProvider:  PATTriggerProducer:patTrigger  06-Oct-2018 21:53:46 CEST Run: 315489 Event: 47697292
 Error in determining L1T prescales for HLT path: 'HLT_DiEle27_WPTightCaloOnly_L1DoubleEG_v4' with complex L1T seed: [long list of seeds omitted]
```

**Comment by Martin-Grunewald** [comment]
@slava77 
This is a valid error message which goes off after 5 instances or so.
PATTriger would have to be fixed...

**Comment by missirol** [comment]
Trying to tackle this old issue.

This type of error can still be seen in recent RelVals, e.g.
https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-baseline-tests/CMSSW_13_0_X_2023-01-10-2300/el8_amd64_gcc11/-GenuineIntel/matrix-results/136.8311_RunJetHT2017FreMINIAOD/step2_RunJetHT2017FreMINIAOD.log

_Short version_ : I suspect the issue is the choice of GT (no HLT/RECO/PAT changes needed); the problematic steps use `auto:run*_data_relval` while `auto:run*_data` should be used instead.

_Longer version_ : I think the behavior of `HLTPrescaleProvider` is correct (it reports that expected L1T seeds are not found; one could argue on whether that should be a `LogWarning` or a `LogError`). This relates to the L1T menu used by the job, which in turn goes back to the GT. In the example above, the GT is `auto:run2_data_relval`. The latter is the same as `auto:run2_data` except that in `auto:run2_data_relval` the L1T menu tag is a single-IOV tag with a specific L1T menu (in principle, the 'latest Run-2 L1T menu in use for this release cycle'); in this case, this means that this 2016 wf loads the 2018 L1T menu, but reads the HLT results from the 2016 EDM file (2016 HLT menu), thus the mismatch. Loading the "latest" L1T menu (i.e. using `auto:run*_data_relval`) would make sense if the wf also included a step with "L1REPACK + (re)HLT".

I guess that, as a tentative rule of thumb, if the RelVal step (1) contains `--data` and (2) does not contain `--(p|hltP)rocess reHLT`, then its GT should not be a `auto:*_relval` one [*].

[*] Some steps with `-s HARVESTING:* --filetype DQM` or `-s SKIM:LogError+LogErrorMonitor` fall in this category (i.e. use `--conditions auto:*_data_relval` without `--(p|hltP)rocess reHLT`), and they might be considered exceptions to this rule-of-thumb (these cases are probably harmless; I doubt they consume the L1T menu in the GT, but I don't really know).

**Comment by missirol** [comment]
+hlt
