### ISSUE TITLE
silence diagnostics/info-only LogWarnings introduced in HCAL unpacker in #22385

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#22706]
#22385 introduced LogWarnings that are expected to be present in abundance ```nStreams(=8)*20*12 ~``` 2K lines per production job.
Only problems should be displayed as LogWarnings.

The diagnostics/info-only part of the printouts should be demoted to LogInfo or LogDebug or hidden under some "silent" configuration switch.

see also https://hypernews.cern.ch/HyperNews/CMS/get/hcal-cmssw/598/1/1/1/1/1.html

@deguio @jkunkle

**Comment by slava77** [comment]
assign reconstruction

**Comment by deguio** [comment]
Hi @slava77 
as of last night, the message are gone. I've checked run 312851 and I confirm that.
the magic happened at p5 where the digi data frame length for the uMNQIE channels was set to 3, consistently with the length for the other HF channels (calib+physics).

this is the configuration we plan to keep and this is a good solution for now.
we want anyway to improve the way the unpacker handles such cases, but it will be something for the future.

@mariadalfonso

**Comment by fabiocos** [comment]
@deguio @mariadalfonso @slava77 @perrotta is this issue still needed? Is there any activity to improve  further?

**Comment by deguio** [comment]
Hi @fabiocos 
I think that this issue can be closed. the problem with the high rate of warnings is resolved and no changes to the unpacker are foreseen on the short term.

**Comment by slava77** [comment]
On 4/10/18 1:14 AM, Federico De Guio wrote:
> Hi @fabiocos <https://github.com/fabiocos>
> I think that this issue can be closed. the problem with the high rate of
> warnings is resolved and no changes to the unpacker are foreseen on the
> short term.
> 

The problem is still technically there, even though the most recent
source was eliminated at the hardware level.
My understanding of the discussion so far was that the logic of the
unpacker will be updated to not react to channels that should not be
unpacked.

I can propose a partial solution to reduce the print out count down to 1
per module (there are 8 module instances in the typical 8-stream
production jobs), which is plenty enough already.

**Comment by slava77** [comment]
I see that today in cms-hlt there was a report of this warning again

```
%MSG-w Invalid Data:  HcalRawToDigi:hltHcalDigis 27-Apr-2018 16:01:03 CEST  Run: 315106 Event: 51727050
The default QIE10 Collection has 3 samples per digi, while the current data has 6!  This data cannot be included with the default collection.
In order to store this data in the event, it must have a unique tag.  To accomplish this, provide two lists to HcalRawToDigi
1) that specifies the number of samples and 2) that gives tags with which these data are saved.
For example in this case you might add
process.hcalDigis.saveQIE10DataNSamples = cms.untracked.vint32( 6)
process.hcalDigis.saveQIE10DataTags = cms.untracked.vstring( "MYDATA" )
%MSG

```

@deguio 
what is the status of following up on this issue?

**Comment by deguio** [comment]
hi @slava77 
I let @jkunkle comment on this.
my understanding is that a new uHTR was installed in the HCAL crate 38 recently. I think that the agreement is not to have it included in the readout when running in global, but I let @jkunkle confirm.

**Comment by slava77** [comment]
I made #23089 
to reduce the number of redundant messages.

**Comment by slava77** [comment]
+1

consider this somewhat resolved by means of #23089
