### ISSUE TITLE
Add a Production Cut on Proton equal to the one on Electron for MTD, Tracker and CTPPS

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmssw#27343]
See #27299

**Comment by kpedro88** [comment]
assign geometry,simulation

**Comment by kpedro88** [comment]
@ianna what about HGCal?

**Comment by kpedro88** [comment]
HGCal is already addressed in the aforementioned PR

**Comment by fabiocos** [comment]
I do not fully follow the logic choice of detectors to be updated first, anyway with this PR we can track is left to be done.

@vargasa @jan-kaspar please see the needs of Tracker and CTPPS

**Comment by ianna** [comment]
@cvuosalo - The issue is still relevant. The 2021 scenario does not define a production cut on Protons, but a 2018 does. So, it could be undefined for a sub detector if a sub detector does not define it. In reality the sim code sets an undefined proton cut equal to electron. Perhaps, it is sufficient? 

@vargasa , @jan-kaspar - FYI

**Comment by jan-kaspar** [comment]
Thanks @ianna ! I forward to @mundim who is responsible for the PPS simulation. Also FYI @fabferro

**Comment by ianna** [comment]
@jan-kaspar - please, let me know if there are any news on CTPPS. 
@cvuosalo - I suppose, the CTPPS should be integrated in the DB payload?

**Comment by mundim** [comment]
Sorry, somehow I overlooked this thread. I was not aware we have not defined production cuts for 2021. Since the simulation geometry (and all related files) are basically copied from 2018, the cuts should also be the same. However, I have tested the 2021 geometry (including the one in the 112 GT) and it worked fine. But we need to make some more detailed studies about the impact of such cuts.

**Comment by vargasa** [comment]
Due to time constraints I haven't been able to look into this. FYI @mmusich

**Comment by fabiocos** [comment]
@ianna as far as MTD is concerned, this issues should be solved now.

**Comment by civanch** [comment]
+1
