### ISSUE TITLE
End of job crashes in ASAN from end IOV task

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#32492]
In CMSSW_11_3_ASAN_X_2020-12-14-2300 we see a lot of segmentation faults happening at the end of job time. They appear to all have the same traceback

```
#5  <signal handler called>
#6  0x00002b07ab86a7c7 in __memmove_ssse3 () from /lib64/libc.so.6
#7  0x00002b07a74d5e56 in __interceptor_memcpy (dst=0x2b07ef233230, src=0x2b086867e800, size=13781212) at ../../../../libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:790
#8  0x00002b07e6c76dc9 in PixelCPETemplateReco::~PixelCPETemplateReco() () from /cvmfs/cms-ib.cern.ch/nweek-02659/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_ASAN_X_2020-12-14-2300/lib/slc7_amd64_gcc900/libRecoLocalTrackerSiPixelRecHits.so
#9  0x00002b07e6c77152 in PixelCPETemplateReco::~PixelCPETemplateReco() () from /cvmfs/cms-ib.cern.ch/nweek-02659/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_ASAN_X_2020-12-14-2300/lib/slc7_amd64_gcc900/libRecoLocalTrackerSiPixelRecHits.so
#10 0x00002b07e6b88364 in edm::eventsetup::CallbackProxy<edm::eventsetup::Callback<PixelCPETemplateRecoESProducer, std::unique_ptr<PixelClusterParameterEstimator, std::default_delete<PixelClusterParameterEstimator> >, TkPixelCPERecord, edm::eventsetup::CallbackSimpleDecorator<TkPixelCPERecord> >, TkPixelCPERecord, std::unique_ptr<PixelClusterParameterEstimator, std::default_delete<PixelClusterParameterEstimator> > >::invalidateCache() () from /cvmfs/cms-ib.cern.ch/nweek-02659/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_ASAN_X_2020-12-14-2300/lib/slc7_amd64_gcc900/pluginRecoLocalTrackerSiPixelRecHitsPlugins.so
#11 0x00002b07a8273544 in edm::eventsetup::EventSetupRecordImpl::invalidateProxies() () from /cvmfs/cms-ib.cern.ch/nweek-02659/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_ASAN_X_2020-12-14-2300/lib/slc7_amd64_gcc900/libFWCoreFramework.so
#12 0x00002b07a8269dcf in edm::FunctorWaitingTask<edm::eventsetup::EventSetupRecordIOVQueue::startNewIOVAsync(edm::WaitingTaskHolder const&, edm::WaitingTaskList&)::{lambda(edm::LimitedTaskQueue::Resumer)#1}::operator()(edm::LimitedTaskQueue::Resumer)::{lambda(std::__exception_ptr::exception_ptr const*)#1}>::execute() () from /cvmfs/cms-ib.cern.ch/nweek-02659/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_ASAN_X_2020-12-14-2300/lib/slc7_amd64_gcc900/libFWCoreFramework.so
#13 0x00002b07aa6f90f5 in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::process_bypass_loop (this=this@entry=0x2b07b0aefe00, context_guard=..., t=0x2b07b0b08640, isolation=isolation@entry=0) at ../../src/tbb/scheduler.h:630
#14 0x00002b07aa6f93ab in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::local_wait_for_all (this=0x2b07b0aefe00, parent=..., child=<optimized out>) at ../../include/tbb/task.h:1003
#15 0x00002b07aa6f2a57 in tbb::internal::arena::process (this=0x2b07b0c86d00, s=...) at ../../src/tbb/arena.cpp:196
#16 0x00002b07aa6f1420 in tbb::internal::market::process (this=0x2b07b0c87580, j=...) at ../../src/tbb/market.cpp:667
#17 0x00002b07aa6edbcc in tbb::internal::rml::private_worker::run (this=0x2b07b4fcf100) at ../../src/tbb/private_server.cpp:266
#18 0x00002b07aa6eddc9 in tbb::internal::rml::private_worker::thread_routine (arg=<optimized out>) at ../../src/tbb/private_server.cpp:219
#19 0x00002b07ab500ea5 in start_thread () from /lib64/libpthread.so.0
#20 0x00002b07ab81496d in clone () from /lib64/libc.so.6
```

The framework should have waited for that task to complete before doing the end of job processing. 

I believe this is happening now because we switched to always using concurrent LuminosityBlocks and IOVs are tied to LuminosityBlock transitions.

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
I was wrong about the timing. The failing call is happening when it is supposed to as the main thread has the stack trace:

```
#3  <signal handler called>
#4  0x00002b07ab80ec89 in syscall () from /lib64/libc.so.6
#5  0x00002b07aa6eda09 in tbb::internal::futex_wakeup_one (futex=0x2b07b4fcf12c) at ../../include/tbb/machine/linux_common.h:90
#6  tbb::internal::binary_semaphore::V (this=0x2b07b4fcf12c) at ../../src/tbb/semaphore.h:214
#7  tbb::internal::binary_semaphore::V (this=0x2b07b4fcf12c) at ../../src/tbb/semaphore.h:211
#8  rml::internal::thread_monitor::notify (this=0x2b07b4fcf120) at ../../src/tbb/../rml/server/thread_monitor.h:240
#9  tbb::internal::rml::private_worker::wake_or_launch (this=0x2b07b4fcf100) at ../../src/tbb/private_server.cpp:312
#10 tbb::internal::rml::private_server::wake_some (this=<optimized out>, additional_slack=<optimized out>) at ../../src/tbb/private_server.cpp:395
#11 0x00002b07aa6f635a in tbb::internal::generic_scheduler::local_spawn (this=0x2b07b0c7e600, first=<optimized out>, next=<optimized out>) at ../../src/tbb/scheduler.cpp:716
#12 0x00002b07a826da85 in edm::eventsetup::EventSetupRecordIOVQueue::endIOV() () from /cvmfs/cms-ib.cern.ch/nweek-02659/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_ASAN_X_2020-12-14-2300/lib/slc7_amd64_gcc900/libFWCoreFramework.so
#13 0x00002b07a82936c0 in edm::eventsetup::EventSetupsController::endIOVs() () from /cvmfs/cms-ib.cern.ch/nweek-02659/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_ASAN_X_2020-12-14-2300/lib/slc7_amd64_gcc900/libFWCoreFramework.so
#14 0x00000000004134a2 in tbb::interface7::internal::delegated_function<main::{lambda()#1}::operator()() const::{lambda()#1} const, void>::operator()() const ()
#15 0x00002b07aa6f3c42 in tbb::interface7::internal::task_arena_base::internal_execute (this=0x7ffd44fee760, d=...) at ../../src/tbb/arena.cpp:1105
#16 0x0000000000416fd1 in main::{lambda()#1}::operator()() const ()
#17 0x00000000004123ac in main ()
```

**Comment by makortel** [comment]
@wddgit Would you have any ideas?

**Comment by wddgit** [comment]
I will take a look and think about it.

**Comment by Dr15Jones** [comment]
The problem may just lie ij the destructor itself
https://github.com/cms-sw/cmssw/blob/69a515e7435a114bb6f2c220722a4187023b2216/RecoLocalTracker/SiPixelRecHits/src/PixelCPETemplateReco.cc#L97-L99

notice the copy being done. That code is
https://github.com/cms-sw/cmssw/blob/69a515e7435a114bb6f2c220722a4187023b2216/RecoLocalTracker/SiPixelRecHits/src/PixelCPETemplateReco.cc#L97-L99

or depending on what `#define` is used could be
https://github.com/cms-sw/cmssw/blob/77b393df1ad0117498b797f49394588c02f83312/CondFormats/SiPixelTransient/interface/SiPixelTemplate.h#L217

The copy would have copied the pointers but it is still problematic having so many compile time switches in that code.

**Comment by dan131riley** [comment]
The destructor is definitely broken, besides unnecessary copies it shouldn't be doing manual memory management at all.  But I don't see why that would suddenly be giving SEGVs.

**Comment by Dr15Jones** [comment]
I suggest changing 
https://github.com/cms-sw/cmssw/blob/77b393df1ad0117498b797f49394588c02f83312/CondFormats/SiPixelTransient/interface/SiPixelTemplate.h#L219-L221
to 
```C++
std::unique_ptr<float[]> cotbetaY;
std::unique_ptr<float[]> cotbetaX;
std::unique_ptr<float[]> cotalphaX;
```
Then the whole `destroy()` function can go away as the destructor will work properly.

**Comment by makortel** [comment]
I recall the pixel template classes causing stack overflow issues before. Could the copy in the `~PixelCPETemplateReco` of a heavy object cause a stack overflow here as well?

**Comment by makortel** [comment]
This array
https://github.com/cms-sw/cmssw/blob/77b393df1ad0117498b797f49394588c02f83312/CondFormats/SiPixelTransient/interface/SiPixelTemplate.h#L216
alone is ~7.3 MB. I'm suspecting a stack overflow.

**Comment by dan131riley** [comment]
Or just use std::vector<float>.  wrt stack use, it looks to me like SI_PIXEL_TEMPLATE_USE_BOOST isn't defined

https://github.com/cms-sw/cmssw/blob/77b393df1ad0117498b797f49394588c02f83312/CondFormats/SiPixelTransient/interface/SiPixelTemplateDefs.h#L19

so the SiPixelTemplateEntry arrays are huge and the deletes are completely wrong.

**Comment by makortel** [comment]
assign alca

**Comment by makortel** [comment]
assign reconstruction

(the suspected problematic copy of the `SiPixelTemplateStore` is in reco package)

**Comment by makortel** [comment]
Some places more with the same pattern
https://github.com/cms-sw/cmssw/blob/69a515e7435a114bb6f2c220722a4187023b2216/RecoLocalTracker/SiPixelRecHits/src/PixelCPEClusterRepair.cc#L158-L163
(the `thePixelTemp2D_` of `SiPixelTemplateStore2D` apparently does not have the same stack issue since the 2D array is always heap-allocated)

https://github.com/cms-sw/cmssw/blob/69a515e7435a114bb6f2c220722a4187023b2216/FastSimulation/TrackingRecHitProducer/src/PixelTemplateSmearerBase.cc#L128-L132
https://github.com/cms-sw/cmssw/blob/69a515e7435a114bb6f2c220722a4187023b2216/FastSimulation/TrackingRecHitProducer/plugins/TrackingRecHitProducer.cc#L97-L101

`SimTracker/SiPixelDigitizer/plugins/SiPixelChargeReweightingAlgorithm.h` seems to leak the contents of `SiPixelTemplateStore2D`.

**Comment by makortel** [comment]
assign simulation

**Comment by makortel** [comment]
assign fastsim

**Comment by wddgit** [comment]
Just to confirm what Chris already said, I looked at the part of the stack traces related to the concurrent IOV code and it looks like that code is functioning as intended.

**Comment by dan131riley** [comment]
PixelCPEClusterRepair is also causing ASAN crashes.  As @makortel noted, it follows the same pattern.  I'll make a PR for it later today unless someone else is already working on it.

**Comment by makortel** [comment]
@dan131riley The piece of `PixelCPEClusterRepair` using `SiPixelTemplateStore` is already addressed in #32494.

**Comment by Dr15Jones** [comment]
My fix has not been merged so the problem it is meant to address is still happening.

**Comment by makortel** [comment]
+1

The fix was merged some time ago so this issue can be closed.

**Comment by slava77** [comment]
+1

this is apparently fixed

**Comment by christopheralanwest** [comment]
+1

**Comment by civanch** [comment]
+1
