### ISSUE TITLE
several `conddb` tools broken in recent 12_0_X IBs

### ISSUE THREAD

**Issue by mmusich** [cms-sw/cmssw#34378]
on top of https://github.com/cms-sw/cmssw/issues/34349, the following functionalities appear to be broken:

1)
```
cmsrel CMSSW_12_0_X_2021-07-06-2300
CMSSW_12_0_X_2021-07-06-2300/src/
conddb dump 4b97f78682aac6254bbcba54cedbde468202bf5b
[2021-07-07 13:47:11,835] INFO: Connecting to pro [frontier://PromptProd/cms_conditions]
[2021-07-07 13:47:12,450] INFO: Found payload of type SiPixelQuality
[2021-07-07 13:47:16,268] INFO: XML converter for payload class SiPixelQuality found in the built-in library.
[2021-07-07 13:47:16,278] ERROR: invalid signature
```
2)
```
$ conddb search 4b97f78682aac6254bbcba54cedbde468202bf5b
[2021-07-07 13:48:46,273] INFO: Connecting to pro [frontier://PromptProd/cms_conditions]
[2021-07-07 13:48:46,491] INFO: Searching with a limit of 100 results per type of object, starting from the latest inserted ones. If you do not find your object, please try to be more specific or increase the limit of returned results.
Tag  Time Type  Object Type  Synchronization  Insertion Time  Description   
---  ---------  -----------  ---------------  --------------  -----------   
 
[2021-07-07 13:49:28,195] ERROR: string argument without an encoding
```
3)
```
$ conddb showFCSR
[2021-07-07 13:53:52,370] INFO: Connecting to pro [frontier://PromptProd/cms_conditions]
[2021-07-07 13:53:52,924] INFO: Found fcsr for hlt: 342474
[2021-07-07 13:53:53,803] ERROR: Error setting up Tier-0 data service: sequence item 0: expected str instance, int found
```

4)
```
$ conddb diffGlobalTagsAtRun -R 120X_mcRun3_2021_realistic_v1 -T 120X_mcRun3_2021_realistic_Candidate_2021_06_09_14_33_50 --run 1
[2021-07-07 13:57:11,209] INFO: Connecting to pro [frontier://PromptProd/cms_conditions]
[2021-07-07 13:57:11,327] ERROR: '<' not supported between instances of 'str' and 'int'
```

**Comment by smuzaffar** [comment]
@mmusich , `conddb` is using `python3` and it does not break for PY3 IBs. Are these commands you mentioned are not tested via unit tests?

**Comment by mmusich** [comment]
@smuzaffar 

>  Are these commands you mentioned are not tested via unit tests?

no

**Comment by davidlange6** [comment]
These look like classic errors.. I’m trying to reproduce

**Comment by davidlange6** [comment]
> > 
> > $ conddb search 4b97f78682aac6254bbcba54cedbde468202bf5b 
> > [2021-07-07 13:48:46,273] INFO: Connecting to pro [frontier://PromptProd/cms_conditions] 
> > [2021-07-07 13:48:46,491] INFO: Searching with a limit of 100 results per type of object, starting from the latest inserted ones. If you do not find your object, please try to be more specific or increase the limit of returned results. 
> > Tag Time Type Object Type Synchronization Insertion Time Description 
> > --- --------- ----------- --------------- -------------- ----------- 
> > 
> > [2021-07-07 13:49:28,195] ERROR: string argument without an encoding 

Fixed with adding the encoding here

    def size(cell):
        return str( sys.getsizeof( bytearray(cell,'utf8') ) )

**Comment by davidlange6** [comment]
> > 
> > $ conddb diffGlobalTagsAtRun -R 120X_mcRun3_2021_realistic_v1 -T 120X_mcRun3_2021_realistic_Candidate_2021_06_09_14_33_50 --run 1 
> > [2021-07-07 13:57:11,209] INFO: Connecting to pro [frontier://PromptProd/cms_conditions] 
> > [2021-07-07 13:57:11,327] ERROR: '<' not supported between instances of 'str' and 'int' 
> > 

The check on the run number <0 needs a cast - eg add the int() here:

        if(int(args.testRunNumber)<0):

(I get different errors that are perhaps not due to python3?

Exception: Run 1 can't be matched with an existing run in the database.

**Comment by makortel** [comment]
assign db

**Comment by davidlange6** [comment]
> On Jul 7, 2021, at 1:59 PM, Marco Musich ***@***.***> wrote:
> 
> 
> on top of #34349, the following functionalities appear to be broken:
> 
> cmsrel CMSSW_12_0_X_2021-07-06-2300
> CMSSW_12_0_X_2021-07-06-2300/src/
> conddb dump 4b97f78682aac6254bbcba54cedbde468202bf5b
> [2021-07-07 13:47:11,835] INFO: Connecting to pro [frontier://PromptProd/cms_conditions]
> [2021-07-07 13:47:12,450] INFO: Found payload of type SiPixelQuality
> [2021-07-07 13:47:16,268] INFO: XML converter for payload class SiPixelQuality found in the built-in library.
> [2021-07-07 13:47:16,278] ERROR: invalid signature

CondCore/Utilities/python/cond2xml.py line 182 needs a decode, but utf-8 is not sufficient. Maybe @ggovi can suggest something?

Eg, this does not work...

resultXML = obj.write( str(data.decode()) )

**Comment by mmusich** [comment]
and another one:
```
$ conddb --yes copy specialDD4hepTEST_120X_mcRun3_2021_realistic_v1_Candidate_2021_07_07_12_35_50 specialDD4hepTEST_120X_mcRun3_2021_realistic_v1_Candidate_2021_07_07_12_35_50 --destdb sqlite_file:specialDD4hepTEST_120X_mcRun3_2021_realistic_v1_Candidate_2021_07_07_12_35_50.db
[2021-07-07 19:23:36,436] INFO: Connecting to pro [frontier://PromptProd/cms_conditions]
[2021-07-07 19:23:36,603] INFO: Connecting to sqlite_file:specialDD4hepTEST_120X_mcRun3_2021_realistic_v1_Candidate_2021_07_07_12_35_50.db [sqlite:///specialDD4hepTEST_120X_mcRun3_2021_realistic_v1_Candidate_2021_07_07_12_35_50.db]
[2021-07-07 19:23:36,946] INFO: Initializing database...
[2021-07-07 19:23:38,297] INFO: Copying global tag pro::specialDD4hepTEST_120X_mcRun3_2021_realistic_v1_Candidate_2021_07_07_12_35_50 to sqlite_file:specialDD4hepTEST_120X_mcRun3_2021_realistic_v1_Candidate_2021_07_07_12_35_50.db::specialDD4hepTEST_120X_mcRun3_2021_realistic_v1_Candidate_2021_07_07_12_35_50 ...
[2021-07-07 19:23:38,587] INFO: Copying tag pro::TrackProbabilityCalibration_2D_MC53X_v3 to sqlite_file:specialDD4hepTEST_120X_mcRun3_2021_realistic_v1_Candidate_2021_07_07_12_35_50.db::TrackProbabilityCalibration_2D_MC53X_v3 from since=1 selecting insertion time < 2021-07-07 12:35:50
[2021-07-07 19:23:38,635] ERROR: name 'long' is not defined
```

**Comment by davidlange6** [comment]
Adding -v to conddb will give you a file/line number.. long is no longer a thing in python3. Likely just needs to be int() instead of long()

**Comment by mmusich** [comment]
I addressed points 2. 3. and 4. here: https://github.com/cms-sw/cmssw/pull/34392.
About point 5., running it in verbose mode, returns:

```
 conddb --verbose --yes copy specialDD4hepTEST_120X_mcRun3_2021_realistic_v1_Candidate_2021_07_07_12_35_50 specialDD4hepTEST_120X_mcRun3_2021_realistic_v1_Candidate_2021_07_07_12_35_50 --destdb sqlite_file:specialDD4hepTEST_120X_mcRun3_2021_realistic_v1_Candidate_2021_07_07_12_35_50.dba
... 
Traceback (most recent call last):
  File "/tmp/musich/testCondDBTools/CMSSW_12_0_X_2021-07-07-2300/bin/slc7_amd64_gcc900/conddb", line 2926, in <module>
    main()
  File "/tmp/musich/testCondDBTools/CMSSW_12_0_X_2021-07-07-2300/bin/slc7_amd64_gcc900/conddb", line 2915, in main
    return args.func(args)
  File "/tmp/musich/testCondDBTools/CMSSW_12_0_X_2021-07-07-2300/bin/slc7_amd64_gcc900/conddb", line 2021, in copy
    _copy_tag(args, copyTime, session1, session2, tag, tag, timeMap=timeMap)
  File "/tmp/musich/testCondDBTools/CMSSW_12_0_X_2021-07-07-2300/bin/slc7_amd64_gcc900/conddb", line 1772, in _copy_tag
    prev_iov = session1.query(IOV1.since).\
  File "/cvmfs/cms-ib.cern.ch/nweek-02688/slc7_amd64_gcc900/external/py3-sqlalchemy/1.3.11-32800f4f1859bb55f1815d8fd1e3fbfc/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3355, in scalar
    ret = self.one()
  File "/cvmfs/cms-ib.cern.ch/nweek-02688/slc7_amd64_gcc900/external/py3-sqlalchemy/1.3.11-32800f4f1859bb55f1815d8fd1e3fbfc/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3325, in one
    ret = self.one_or_none()
  File "/cvmfs/cms-ib.cern.ch/nweek-02688/slc7_amd64_gcc900/external/py3-sqlalchemy/1.3.11-32800f4f1859bb55f1815d8fd1e3fbfc/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3294, in one_or_none
    ret = list(self)
  File "/cvmfs/cms-ib.cern.ch/nweek-02688/slc7_amd64_gcc900/external/py3-sqlalchemy/1.3.11-32800f4f1859bb55f1815d8fd1e3fbfc/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "/cvmfs/cms-ib.cern.ch/nweek-02688/slc7_amd64_gcc900/external/py3-sqlalchemy/1.3.11-32800f4f1859bb55f1815d8fd1e3fbfc/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/cvmfs/cms-ib.cern.ch/nweek-02688/slc7_amd64_gcc900/external/py3-sqlalchemy/1.3.11-32800f4f1859bb55f1815d8fd1e3fbfc/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/cvmfs/cms-ib.cern.ch/nweek-02688/slc7_amd64_gcc900/external/py3-sqlalchemy/1.3.11-32800f4f1859bb55f1815d8fd1e3fbfc/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/cvmfs/cms-ib.cern.ch/nweek-02688/slc7_amd64_gcc900/external/py3-sqlalchemy/1.3.11-32800f4f1859bb55f1815d8fd1e3fbfc/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1095, in _execute_clauseelement
    ret = self._execute_context(
  File "/cvmfs/cms-ib.cern.ch/nweek-02688/slc7_amd64_gcc900/external/py3-sqlalchemy/1.3.11-32800f4f1859bb55f1815d8fd1e3fbfc/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    self._handle_dbapi_exception(
  File "/cvmfs/cms-ib.cern.ch/nweek-02688/slc7_amd64_gcc900/external/py3-sqlalchemy/1.3.11-32800f4f1859bb55f1815d8fd1e3fbfc/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1478, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/cvmfs/cms-ib.cern.ch/nweek-02688/slc7_amd64_gcc900/external/py3-sqlalchemy/1.3.11-32800f4f1859bb55f1815d8fd1e3fbfc/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/cvmfs/cms-ib.cern.ch/nweek-02688/slc7_amd64_gcc900/external/py3-sqlalchemy/1.3.11-32800f4f1859bb55f1815d8fd1e3fbfc/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "/cvmfs/cms-ib.cern.ch/nweek-02688/slc7_amd64_gcc900/external/py3-sqlalchemy/1.3.11-32800f4f1859bb55f1815d8fd1e3fbfc/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "/cvmfs/cms-ib.cern.ch/nweek-02688/slc7_amd64_gcc900/external/frontier_client/2.9.1-36aa3d16db1a2f3f5da5848ef71f61c1/python/lib/frontier.py", line 254, in execute
    operation = operation.replace(variable,_stringify(parameters[variable[1:]]))
  File "/cvmfs/cms-ib.cern.ch/nweek-02688/slc7_amd64_gcc900/external/frontier_client/2.9.1-36aa3d16db1a2f3f5da5848ef71f61c1/python/lib/frontier.py", line 149, in _stringify
    elif isinstance(parameter, int) or isinstance(parameter, long) or isinstance(parameter, float):
NameError: name 'long' is not defined
```

I am under the impression it requires changes in some external file (`frontier_client`)?

**Comment by ggovi** [comment]
I have a PR ready to be issued fixing the 4 items above and more that I've found. However, it does not fix item 5, that requires fixes to the frontier sqlalchemy plugin.

**Comment by ggovi** [comment]
The above problem should be probably easy to fix, replacing long with int... but other issue will appear!

**Comment by ggovi** [comment]
Addressed by https://github.com/cms-sw/cmssw/pull/34402
The frontier sqlalchemy plugin needs still to be fixed...

**Comment by mmusich** [comment]
I think this issue can be signed and closed.

**Comment by ggovi** [comment]
+1
