### ISSUE TITLE
Comparison failed for tests of wf `39434.911`

### ISSUE THREAD

**Issue by francescobrivio** [cms-sw/cmssw#37315]
In recent PRs test results there is a message saying:
```
comparisons for the following workflows were not done due to missing matrix map:
 - /data/cmsbld/jenkins/workspace/compare-root-files-short-matrix/data/PR-cadc83/39434.911_TTbar_14TeV+2026D88_DD4hep+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal
```
But nonetheless the default comparison reports more than 50k differences for this wf.
Some examples:
 - #37265 
 - #37294
 - #37288 
 - ...

**Comment by francescobrivio** [comment]
assign reconstruction

**Comment by jpata** [comment]
.911 is dd4hep, we often had differences in it not related to reco. did something change, or is it still a geometry-related issue?

**Comment by makortel** [comment]
I believe the message

> ```
> comparisons for the following workflows were not done due to missing matrix map:
>  - /data/cmsbld/jenkins/workspace/compare-root-files-short-matrix/data/PR-cadc83/39434.911_TTbar_14TeV+2026D88_DD4hep+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal
> ```

refers only to the "validateJR" / "reco comparisons", and not to RelMon-based comparisons or DQM bin by bin.

**Comment by perrotta** [comment]
> I believe the message
> 
> > ```
> > comparisons for the following workflows were not done due to missing matrix map:
> >  - /data/cmsbld/jenkins/workspace/compare-root-files-short-matrix/data/PR-cadc83/39434.911_TTbar_14TeV+2026D88_DD4hep+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal
> > ```
> 
> refers only to the "validateJR" / "reco comparisons", and not to RelMon-based comparisons or DQM bin by bin.

There are however also quite a lot of differences in the bin by bin DQM comparisons for that workflow in the test outputs, as you can verify by opening any of the links to the PR tests listed in the issue description above.

**Comment by makortel** [comment]
> > I believe the message
> > > ```
> > > comparisons for the following workflows were not done due to missing matrix map:
> > >  - /data/cmsbld/jenkins/workspace/compare-root-files-short-matrix/data/PR-cadc83/39434.911_TTbar_14TeV+2026D88_DD4hep+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal
> > > ```
> > 
> > 
> > refers only to the "validateJR" / "reco comparisons", and not to RelMon-based comparisons or DQM bin by bin.
> 
> There are however also quite a lot of differences in the bin by bin DQM comparisons for that workflow in the test outputs, as you can verify by opening any of the links to the PR tests listed in the issue description above.

Right, but the existence of the differences (whose cause should be identified) is a separate issue from one piece of comparisons infrastructure not recognizing this workflow.

**Comment by cvuosalo** [comment]
39434.911 is Phase 2 D88 DD4hep. It is quite new and may be still under development.
@srimanob Could you please comment about the stability of this workflow?

This workflow runs DD4hep from XML files. That makes it very sensitive to any perturbations in the source files or test process.

**Comment by cvuosalo** [comment]
assign upgrade

**Comment by srimanob** [comment]
How can we test the stability of the workflow offline? I mean how do we know if some unexpected random will happen somewhere without this kind of PR test.

The test was done with ttbar 9k events, but that is to compare between DDD and DD4hep. I never try to compare DD4hep with DD4hep from 2 runs to see its stability.

**Comment by francescobrivio** [comment]
@cvuosalo @srimanob what I find strange is that in all the tests there are ~50k failed differences over ~100k total comparisons (see [this log](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_4_X_2022-03-22-1100+cadc83/49072/39434.911_TTbar_14TeV+2026D88_DD4hep+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal/) for example). So, if basically half of the comparisons fail, maybe it's not just a "stability" problem?

**Comment by srimanob** [comment]
@francescobrivio 
Yes, I saw it. I can comment it out for now. Clearly, this is not expected.  However, as I said, I still have no idea why and how I can test it offline. SInce now we allow to create baseline in PR test (https://github.com/cms-sw/cmssw/issues/37289), this may help when I try to enable it.

**Comment by makortel** [comment]
@srimanob Could you elaborate what you mean with "test it offline"? Is it e.g. about comparing the DQM root files of different invocations of the workflow?

**Comment by srimanob** [comment]
Hi @makortel 
I mean I don't expect the change in .911 DD4hep phase-2 wf. With the test results on several PRs that show failure on comparison, should I test it locally somehow. For example, run twices with and without PR and compare locallly?

By the way, last fresh test of the following PR does not show perculiar on the workflow comparison,
- https://github.com/cms-sw/cmssw/pull/37324

**Comment by makortel** [comment]
> For example, run twices with and without PR and compare locallly?

Right, run twice or many times. The comparison failure appears to be random, so it is hard to say beforehand how many times to run. In the past we've seen occurrence rates between O(1 %) and O(100 %) or so with the (Run 3) DD4Hep workflow.

**Comment by clacaputo** [comment]
> ```
> comparisons for the following workflows were not done due to missing matrix map:
>  - /data/cmsbld/jenkins/workspace/compare-root-files-short-matrix/data/PR-cadc83/39434.911_TTbar_14TeV+2026D88_DD4hep+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal
> ```

I think this problem should be addressed by this https://github.com/cms-sw/cms-bot/commit/31e5f20d2670b54ae41e2100a668d1cf86128121

**Comment by srimanob** [comment]
I've prepared the pull request to disable it in case we still face _random_ issue of failure comparison.
https://github.com/cms-sw/cmssw/pull/37337

**Comment by jpata** [comment]
+reconstruction
- looks like the 39434.911 was disabled
