### ISSUE TITLE
segmentation faults in TNamed::Clone()

### ISSUE THREAD

**Issue by dan131riley** [cms-sw/cmssw#40290]
In the CMSSW_13_0_X_2022-12-12-1100 IB, we're seeing several crashes in `TNamed::Clone()` and `TObject::Clone` (and one in `TDirectory::RegisterContext`), in step1 of WF 2017.6, 25405.0, 25407.0, 25408.0, 250403.17, 250403.18, 250407.17, 250408.18 (at least).  The PRs merged in that IB look pretty innocuous?

**Comment by makortel** [comment]
assign core

**Comment by Dr15Jones** [comment]
It looks like the three in el8_amd64_gcc10/CMSSW_13_0_X_2022-12-12-1100 which crash in TClone have the following stack trace

```
#4  <signal handler called>
#5  0x00002b0e46755885 in TObject::Clone(char const*) const () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_13_0_X_2022-12-12-1100/external/el8_amd64_gcc10/lib/libCore.so
#6  0x00002b0e4675453d in TNamed::Clone(char const*) const () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_13_0_X_2022-12-12-1100/external/el8_amd64_gcc10/lib/libCore.so
#7  0x00002b0e462c83a9 in TStreamerInfo::Clone(char const*) const () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_13_0_X_2022-12-12-1100/external/el8_amd64_gcc10/lib/libRIO.so
#8  0x00002b0e462d7993 in TStreamerInfo::GenerateInfoForPair(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, unsigned long, unsigned long) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_13_0_X_2022-12-12-1100/external/el8_amd64_gcc10/lib/libRIO.so
#9  0x00002b0e462ce534 in TStreamerInfo::GenerateInfoForPair(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, unsigned long, unsigned long) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_13_0_X_2022-12-12-1100/external/el8_amd64_gcc10/lib/libRIO.so
#10 0x00002b0e468124c4 in TClass::GetClass(char const*, bool, bool, unsigned long, unsigned long) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_13_0_X_2022-12-12-1100/external/el8_amd64_gcc10/lib/libCore.so
#11 0x00002b0e462b946d in TGenCollectionProxy::InitializeEx(bool) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_13_0_X_2022-12-12-1100/external/el8_amd64_gcc10/lib/libRIO.so
#12 0x00002b0e462b5a97 in TGenCollectionProxy::Generate() const () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_13_0_X_2022-12-12-1100/external/el8_amd64_gcc10/lib/libRIO.so
#13 0x00002b0e468075c4 in TClass::GetCollectionProxy() const () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_13_0_X_2022-12-12-1100/external/el8_amd64_gcc10/lib/libCore.so
#14 0x00002b0e462e39c6 in TStreamerInfo::Build(bool) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_13_0_X_2022-12-12-1100/external/el8_amd64_gcc10/lib/libRIO.so
#15 0x00002b0e468091cc in TClass::GetStreamerInfoImpl(int, bool) const () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_13_0_X_2022-12-12-1100/external/el8_amd64_gcc10/lib/libCore.so
#16 0x00002b0e4680934a in TClass::GetStreamerInfo(int, bool) const () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_13_0_X_2022-12-12-1100/external/el8_amd64_gcc10/lib/libCore.so
#17 0x00002b0e462b5f52 in TGenCollectionProxy::GetWriteMemberWiseActions() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_13_0_X_2022-12-12-1100/external/el8_amd64_gcc10/lib/libRIO.so
#18 0x00002b0e46484a11 in int TStreamerInfo::WriteBufferAux<char**>(TBuffer&, char** const&, TStreamerInfo::TCompInfo* const*, int, int, int, int, int) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_13_0_X_2022-12-12-1100/external/el8_amd64_gcc10/lib/libRIO.so
#19 0x00002b0e462e5b3d in TStreamerInfoActions::GenericWriteAction(TBuffer&, void*, TStreamerInfoActions::TConfiguration const*) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_13_0_X_2022-12-12-1100/external/el8_amd64_gcc10/lib/libRIO.so
#20 0x00002b0e4621c6bd in TBufferFile::WriteClassBuffer(TClass const*, void*) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_13_0_X_2022-12-12-1100/external/el8_amd64_gcc10/lib/libRIO.so
#21 0x00002b0e46216f43 in TBufferFile::WriteFastArray(void*, TClass const*, int, TMemberStreamer*) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_13_0_X_2022-12-12-1100/external/el8_amd64_gcc10/lib/libRIO.so
#22 0x00002b0e4648206a in int TStreamerInfo::WriteBufferAux<char**>(TBuffer&, char** const&, TStreamerInfo::TCompInfo* const*, int, int, int, int, int) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_13_0_X_2022-12-12-1100/external/el8_amd64_gcc10/lib/libRIO.so
#23 0x00002b0e462e5b3d in TStreamerInfoActions::GenericWriteAction(TBuffer&, void*, TStreamerInfoActions::TConfiguration const*) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_13_0_X_2022-12-12-1100/external/el8_amd64_gcc10/lib/libRIO.so
#24 0x00002b0e462161e5 in TBufferFile::ApplySequence(TStreamerInfoActions::TActionSequence const&, void*) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_13_0_X_2022-12-12-1100/external/el8_amd64_gcc10/lib/libRIO.so
#25 0x00002b0e45cde8de in TBranch::FillImpl(ROOT::Internal::TBranchIMTHelper*) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_13_0_X_2022-12-12-1100/external/el8_amd64_gcc10/lib/libTree.so
#26 0x00002b0e45ceb6cb in TBranchElement::FillImpl(ROOT::Internal::TBranchIMTHelper*) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_13_0_X_2022-12-12-1100/external/el8_amd64_gcc10/lib/libTree.so
#27 0x00002b0e45ceb3c9 in TBranchElement::FillImpl(ROOT::Internal::TBranchIMTHelper*) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_13_0_X_2022-12-12-1100/external/el8_amd64_gcc10/lib/libTree.so
#28 0x00002b0e45d58af0 in TTree::Fill() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_13_0_X_2022-12-12-1100/external/el8_amd64_gcc10/lib/libTree.so
```

So it looks like there is a problem related to `std::pair<>` ?

@pcanal any thoughts?

**Comment by Dr15Jones** [comment]
So I just tried running workflow 2017.6 with a single thread in CMSSW_13_0_X_2022-12-12-1100 on slc7_amd64_gcc11 using a single thread and the job finished fine. Now to try with multiple threads.

**Comment by Dr15Jones** [comment]
So one of the TClones crashes happens at the same time as the job is reading from a TFile via the changes I made to HFShowerLibrary

```
#3  <signal handler called>
#4  0x00002b0e47d79ab4 in read () from /lib64/libpthread.so.0
#5  0x00002b0e4af8582c in edm::storage::File::read(void*, unsigned long) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02763/el8_amd64_gcc10/cms/cmssw/CMSSW_13_0_X_2022-12-11-0000/lib/el8_amd64_gcc10/libUtilitiesStorageFactory.so
#6  0x00002b0e4af818e4 in edm::storage::StorageAccountProxy::read(void*, unsigned long) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02763/el8_amd64_gcc10/cms/cmssw/CMSSW_13_0_X_2022-12-11-0000/lib/el8_amd64_gcc10/libUtilitiesStorageFactory.so
#7  0x00002b0e4af7ad35 in edm::storage::Storage::xread(void*, unsigned long) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02763/el8_amd64_gcc10/cms/cmssw/CMSSW_13_0_X_2022-12-11-0000/lib/el8_amd64_gcc10/libUtilitiesStorageFactory.so
#8  0x00002b0e4c430561 in TStorageFactoryFile::ReadBuffer(char*, int) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02763/el8_amd64_gcc10/cms/cmssw/CMSSW_13_0_X_2022-12-11-0000/lib/el8_amd64_gcc10/libIOPoolTFileAdaptor.so
#9  0x00002b0e45cd0f08 in TBasket::ReadBasketBuffers(long long, int, TFile*) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_13_0_X_2022-12-12-1100/external/el8_amd64_gcc10/lib/libTree.so
#10 0x00002b0e45cdb819 in TBranch::GetBasketImpl(int, TBuffer*) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_13_0_X_2022-12-12-1100/external/el8_amd64_gcc10/lib/libTree.so
#11 0x00002b0e45cdcead in TBranch::GetBasketAndFirst(TBasket*&, long long&, TBuffer*) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_13_0_X_2022-12-12-1100/external/el8_amd64_gcc10/lib/libTree.so
#12 0x00002b0e45cdd0a7 in TBranch::GetEntry(long long, int) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_13_0_X_2022-12-12-1100/external/el8_amd64_gcc10/lib/libTree.so
#13 0x00002b0e45cf7b98 in TBranchElement::GetEntry(long long, int) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_13_0_X_2022-12-12-1100/external/el8_amd64_gcc10/lib/libTree.so
#14 0x00002b0e94a4867d in HFShowerLibrary::BranchReader::getRecordNewFormV3(TBranch*, int) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_13_0_X_2022-12-12-1100/lib/el8_amd64_gcc10/libSimG4CMSCalo.so
#15 0x00002b0e94a48900 in HFShowerLibrary::BranchReader::getRecord(int) const () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_13_0_X_2022-12-12-1100/lib/el8_amd64_gcc10/libSimG4CMSCalo.so
#16 0x00002b0e94a489a2 in HFShowerLibrary::getRecord(int, int) const () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_13_0_X_2022-12-12-1100/lib/el8_amd64_gcc10/libSimG4CMSCalo.so
#17 0x00002b0e94a48d9b in HFShowerLibrary::interpolate(int, double) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_13_0_X_2022-12-12-1100/lib/el8_amd64_gcc10/libSimG4CMSCalo.so
#18 0x00002b0e94a4a2f8 in HFShowerLibrary::fillHits(CLHEP::Hep3Vector const&, CLHEP::Hep3Vector const&, int, double, bool&, double, double, bool) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_13_0_X_2022-12-12-1100/lib/el8_amd64_gcc10/libSimG4CMSCalo.so
#19 0x00002b0e9499e6da in FastHFShowerLibrary::recoHFShowerLibrary(FSimTrack const&) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_13_0_X_2022-12-12-1100/lib/el8_amd64_gcc10/libFastSimulationShowerDevelopment.so
#20 0x00002b0e948504ec in CalorimetryManager::HDShowerSimulation(FSimTrack const&, RandomEngineAndDistribution const*) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_13_0_X_2022-12-12-1100/lib/el8_amd64_gcc10/libFastSimulationCalorimetry.so
#21 0x00002b0e948527ff in CalorimetryManager::reconstructTrack(FSimTrack&, RandomEngineAndDistribution const*) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_13_0_X_2022-12-12-1100/lib/el8_amd64_gcc10/libFastSimulationCalorimetry.so
#22 0x00002b0e947e8975 in FastSimProducer::produce(edm::Event&, edm::EventSetup const&) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_13_0_X_2022-12-12-1100/lib/el8_amd64_gcc10/pluginFastSimulationSimplifiedGeometryPropagatorAuto.so
```

However, the other two jobs which crash in TClone do not have something similar in their call stacks.

**Comment by Dr15Jones** [comment]
I ran the step1 of workflow 2017.6 using 4 threads. I tried 4 times and it never failed. So this problem is hard to reproduce.

**Comment by dan131riley** [comment]
I'm on my fourth run of 250407.17 in el8_amd64_gcc10/CMSSW_13_0_X_2022-12-12-1100, hasn't replicated.

**Comment by Dr15Jones** [comment]
So the code for `Directory::RegisterContext` is doing a while loop over a linked list. Looks like that list has been corrupted.


void [TDirectory::RegisterContext](https://root.cern.ch/doc/master/classTDirectory.html#aeff0e0841737d2efe9045f8d47dfeac8)([TContext](https://root.cern.ch/doc/master/classTDirectory_1_1TContext.html) *ctxt) {
 1304   [ROOT::Internal::TSpinLockGuard](https://root.cern.ch/doc/master/classROOT_1_1Internal_1_1TSpinLockGuard.html) slg([fSpinLock](https://root.cern.ch/doc/master/classTDirectory.html#a400e242426a46465ec256f8090fd0796));
 1305 
 1306   if ([fContext](https://root.cern.ch/doc/master/classTDirectory.html#a5d8f223ff5a9bfe1d235e671a4b11127)) {
 1307      [TContext](https://root.cern.ch/doc/master/classTDirectory_1_1TContext.html) *current = [fContext](https://root.cern.ch/doc/master/classTDirectory.html#a5d8f223ff5a9bfe1d235e671a4b11127);
 1308      while(current->[fNext](https://root.cern.ch/doc/master/classTDirectory_1_1TContext.html#abf70c6a947956452abf7a6693594ac2b)) {
 1309         current = current->[fNext](https://root.cern.ch/doc/master/classTDirectory_1_1TContext.html#abf70c6a947956452abf7a6693594ac2b);
 1310      }
 1311      current->[fNext](https://root.cern.ch/doc/master/classTDirectory_1_1TContext.html#abf70c6a947956452abf7a6693594ac2b) = ctxt;
 1312      ctxt->[fPrevious](https://root.cern.ch/doc/master/classTDirectory_1_1TContext.html#aa8af5626e3d3790bbd3af75642223294) = current;
 1313   } else {
 1314      [fContext](https://root.cern.ch/doc/master/classTDirectory.html#a5d8f223ff5a9bfe1d235e671a4b11127) = ctxt;
 1315   }
 1316}

**Comment by dan131riley** [comment]
Got a crash, retrying with a debug TDirectory.cxx.
```
#0  0x00007f9f46758470 in ?? ()
#1  0x00007fa01d882eb4 in TDirectory::TContext::~TContext() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_13_0_X_2022-12-12-1100/external/el8_amd64_gcc10/lib/libCore.so
#2  0x00007fa01dcf5483 in TDirectoryFile::Save() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_13_0_X_2022-12-12-1100/external/el8_amd64_gcc10/lib/libRIO.so
#3  0x00007fa01dcf51cc in TDirectoryFile::Close(char const*) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_13_0_X_2022-12-12-1100/external/el8_amd64_gcc10/lib/libRIO.so
#4  0x00007fa01dd1203c in TFile::Close(char const*) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_13_0_X_2022-12-12-1100/external/el8_amd64_gcc10/lib/libRIO.so
#5  0x00007f9f8b73fa8e in edm::InputFile::Close() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02763/el8_amd64_gcc10/cms/cmssw/CMSSW_13_0_X_2022-12-11-0000/lib/el8_amd64_gcc10/pluginIOPoolInput.so
#6  0x00007f9f8b73fb49 in edm::InputFile::~InputFile() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02763/el8_amd64_gcc10/cms/cmssw/CMSSW_13_0_X_2022-12-11-0000/lib/el8_amd64_gcc10/pluginIOPoolInput.so
#7  0x00007f9f8b74204a in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02763/el8_amd64_gcc10/cms/cmssw/CMSSW_13_0_X_2022-12-11-0000/lib/el8_amd64_gcc10/pluginIOPoolInput.so
#8  0x00007f9f8b768cf5 in edm::RootFile::~RootFile() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02763/el8_amd64_gcc10/cms/cmssw/CMSSW_13_0_X_2022-12-11-0000/lib/el8_amd64_gcc10/pluginIOPoolInput.so
#9  0x00007f9f8b75a552 in edm::RootEmbeddedFileSequence::closeFile_() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02763/el8_amd64_gcc10/cms/cmssw/CMSSW_13_0_X_2022-12-11-0000/lib/el8_amd64_gcc10/pluginIOPoolInput.so
#10 0x00007f9f8b73b450 in edm::EmbeddedRootSource::endJob() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02763/el8_amd64_gcc10/cms/cmssw/CMSSW_13_0_X_2022-12-11-0000/lib/el8_amd64_gcc10/pluginIOPoolInput.so
#11 0x00007f9fa560e2d0 in edm::BMixingModule::endStream() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02763/el8_amd64_gcc10/cms/cmssw/CMSSW_13_0_X_2022-12-11-0000/lib/el8_amd64_gcc10/libMixingBase.so
```

**Comment by pcanal** [comment]
So the last time, I saw something similar the case was akin to:
* use TFile (a) in thread (1)
* store pointer of TFile (a) in some list (eg. the list of context)
* use TFile (b) in thread (2) and delete it .. but 'forget' to remove it from the list.
* die in thread (1) when walking list 

Let me try to find the actual context and resolution.

**Comment by Dr15Jones** [comment]
As part of my changes to HFShowerLibrary, I actually had the class take ownership of the `TFile` it opened.

https://github.com/cms-sw/cmssw/blob/547b357c4a6b16df03a47f1afec6fd3425891c94/SimG4CMS/Calo/interface/HFShowerLibrary.h#L134

https://github.com/cms-sw/cmssw/blob/547b357c4a6b16df03a47f1afec6fd3425891c94/SimG4CMS/Calo/src/HFShowerLibrary.cc#L104

The previous code called `TFile::Open` but never deleted the pointer.

**Comment by makortel** [comment]
All these kind of job failures were in FastSim workflows. It makes me wonder if FastSim uses the HFShowerLibrary in some "special" way? (@cms-sw/fastsim-l2)

**Comment by Dr15Jones** [comment]
> All these kind of job failures were in FastSim workflows. It makes me wonder if FastSim uses the HFShowerLibrary in some "special" way? 

I was just looking at that. It does, it creates/destroys a new HFShowerLibrary each event.

**Comment by makortel** [comment]
> The issue I referred to is: [root-project/root#6939](https://github.com/root-project/root/issues/6939). Probably completely related but slightly different.

Just for the record, here is an issue https://github.com/cms-sw/cmssw/issues/15524 and PR https://github.com/cms-sw/cmssw/pull/15670 for a similar case in CMSSW.

**Comment by Dr15Jones** [comment]
I will make a PR changing HFShowerLibrary to protect the opening of the TFile via `TDirectory::TContext context;`. I will go on record stating that I believe this is should be considered a flaw in ROOT, not an improvement.

**Comment by Dr15Jones** [comment]
The fast sim behavior should be fixed with #40297.

**Comment by makortel** [comment]
> On the first event, both calls to `check` would return true, but C++ short circuits `||` so only the first call to `check` is made. On the second event, the first call to `check` now returns `false` so the second `check` is now called and it returns `true` since it is the first time it has checked an event.

Quick `git grep "check(.*) || .*check(.*)"` shows similar pattern in
```
CommonTools/ParticleFlow/plugins/PFCandidateRecalibrator.cc
DQM/SiStripMonitorSummary/plugins/SiStripCorrelateBadStripAndNoise.cc
RecoEgamma/EgammaElectronAlgos/src/ElectronSeedGenerator.cc
```
Would these be worth of taking a closer look too?

**Comment by pcanal** [comment]
I have not been able to reproduce the `TContext` crashes yet.  I.e. the actual situation is a bit more complicated that I thought so far (but I still have a few things to try).  Looking at the code though, it should have worked (I think), so indeed a bug in `TContext`.

**Comment by pcanal** [comment]
>to protect the opening of the TFile via TDirectory::TContext context;

Even-though, it should not have been needed, it is still probably a good idea in order to reduce the side-effects and interconnect (Using the `TContext` while both insure that this thread `gDirectory` is not pointing to the file while it is being used by another thread and will also prevent code still relying on auto-registration of histogram/tree to put them in the wrong file).

> I have not been able to reproduce the TContext crashes yet.

I have a theoretical possibility:

(1) thread one create `TFile, `gDirectory` now points to that file.
(2) thread two delete `TFile`, the destructor calls `CleanTargets` which has 4 distinct phase
(a) take the `TFile` spin lock and update all the `TContext` that points to the file 
(b) still hold the spin lock, clean the other thread's directory.
(c) deal with the `TContext` that were being destructed at the same time
(d) update the local gDirectory

If between (2)(a) and (2)(b), thread (1) starts the creation of a `TContext`, and is held at the start of `RegisterContet`
after thread 2 release the spin lock, thread 1 might awaken only after the `TFile` object has been deleted and thus `RegisterContext` would access delete memory.

If during the destruction of the `TFile` by thread 2,  thread (1) starts the creation of a `TContext`, but is suspend right before the start of `RegisterContext`, when it comes back it will use deleted memory to try to acquire the spin lock.

**Comment by pcanal** [comment]
and I found a way to reproduce the reproduce the later of the 2 failing case.

**Comment by dan131riley** [comment]
With these changes (the first equivalent to Chris's PR and the second just adding the TContext), I've so far been unable to reproduce the crash:
```
diff --git a/FastSimulation/SimplifiedGeometryPropagator/plugins/FastSimProducer.cc b/FastSimulation/SimplifiedGeometryPropagator/plugins/FastSimProducer.cc
index ee4ba8d..973838a 100644
--- a/FastSimulation/SimplifiedGeometryPropagator/plugins/FastSimProducer.cc
+++ b/FastSimulation/SimplifiedGeometryPropagator/plugins/FastSimProducer.cc
@@ -203,7 +203,9 @@ void FastSimProducer::produce(edm::Event& iEvent, const edm::EventSetup& iSetup)

   //  Initialize the calorimeter geometry
   if (simulateCalorimetry) {
-    if (watchCaloGeometry_.check(iSetup) || watchCaloTopology_.check(iSetup)) {
+    auto geom = watchCaloGeometry_.check(iSetup);
+    auto topo = watchCaloTopology_.check(iSetup);
+    if (geom || topo) {
       auto const& pG = iSetup.getData(caloGeometryESToken_);
       myCalorimetry->getCalorimeter()->setupGeometry(pG);

diff --git a/SimG4CMS/Calo/src/HFShowerLibrary.cc b/SimG4CMS/Calo/src/HFShowerLibrary.cc
index a1651ad..e76cf71 100644
--- a/SimG4CMS/Calo/src/HFShowerLibrary.cc
+++ b/SimG4CMS/Calo/src/HFShowerLibrary.cc
@@ -101,7 +101,10 @@ HFShowerLibrary::HFShowerLibrary(const Params& iParams, const FileParams& iFileP
   std::string pTreeName = iFileParams.fileName_;

   const char* nTree = pTreeName.c_str();
-  hf_ = std::unique_ptr<TFile>(TFile::Open(nTree));
+  {
+    TDirectory::TContext contextEraser;
+    hf_ = std::unique_ptr<TFile>(TFile::Open(nTree));
+  }

   if (!hf_->IsOpen()) {
     edm::LogError("HFShower") << "HFShowerLibrary: opening " << nTree << " failed";
```

**Comment by pcanal** [comment]
The problem was actually simpler (and less rare than my original speculation).  It is now tracked at https://github.com/root-project/root/issues/11907 and will be fixed shortly.  The issue is that if a thread local `gDirectory` points to a file that is deleted by another threads, that `gDirectory` (with the ROOT version used here) is not updated and let the code continue to use this deleted objects (including `TContext`).
