### ISSUE TITLE
[ASAN_X]  ERROR: AddressSanitizer: stack-buffer-overflow

### ISSUE THREAD

**Issue by akritkbehera** [cms-sw/cmssw#48495]
In CMSSW_15_1_ASAN_X_2025-07-07-2300 several RelVals failed with `stack-buffer-overflow on address` error
```BASH
==992550==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x155346464390 at pc 0x1552db11558c bp 0x1553464567a0 sp 0x155346456798
READ of size 4 at 0x155346464390 thread T3
    #0 0x1552db11558b in Phase2L1CaloPFClusterEmulator::produce(edm::Event&, edm::EventSetup const&) (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02897/el8_amd64_gcc12/cms/cmssw/CMSSW_15_1_ASAN_X_2025-07-07-2300/lib/el8_amd64_gcc12/pluginL1TriggerL1CaloTriggerAuto.so+0x51558b)
    #1 0x1553a609cf85 in edm::stream::EDProducerAdaptorBase::doEvent(edm::EventTransitionInfo const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02897/el8_amd64_gcc12/cms/cmssw/CMSSW_15_1_ASAN_X_2025-07-07-2300/lib/el8_amd64_gcc12/libFWCoreFramework.so+0xa9cf85)
    #2 0x1553a5ffb238 in edm::WorkerT<edm::stream::EDProducerAdaptorBase>::implDo(edm::EventTransitionInfo const&, edm::ModuleCallingContext const*) (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02897/el8_amd64_gcc12/cms/cmssw/CMSSW_15_1_ASAN_X_2025-07-07-2300/lib/el8_amd64_gcc12/libFWCoreFramework.so+0x9fb238)
    #3 0x1553a5c51de9 in decltype ({parm#1}()) edm::convertException::wrap<edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}>(edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}) (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02897/el8_amd64_gcc12/cms/cmssw/CMSSW_15_1_ASAN_X_2025-07-07-2300/lib/el8_amd64_gcc12/libFWCoreFramework.so+0x651de9)
    #4 0x1553a5c524eb in std::__exception_ptr::exception_ptr edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(std::__exception_ptr::exception_ptr, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02897/el8_amd64_gcc12/cms/cmssw/CMSSW_15_1_ASAN_X_2025-07-07-2300/lib/el8_amd64_gcc12/libFWCoreFramework.so+0x6524eb)
    #5 0x1553a5c6303c in edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >::execute() (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02897/el8_amd64_gcc12/cms/cmssw/CMSSW_15_1_ASAN_X_2025-07-07-2300/lib/el8_amd64_gcc12/libFWCoreFramework.so+0x66303c)
    #6 0x1553a6bb4072 in tbb::detail::d2::function_task<edm::WaitingTaskList::announce()::{lambda()#1}>::execute(tbb::detail::d1::execution_data&) (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02897/el8_amd64_gcc12/cms/cmssw/CMSSW_15_1_ASAN_X_2025-07-07-2300/lib/el8_amd64_gcc12/libFWCoreConcurrency.so+0x17072)
    #7 0x1553a516e609 in tbb::detail::d1::task* tbb::detail::r1::task_dispatcher::local_wait_for_all<false, tbb::detail::r1::outermost_worker_waiter>(tbb::detail::d1::task*, tbb::detail::r1::outermost_worker_waiter&) /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc12/external/tbb/v2022.0.0-79b5a917b0c13f831cd534a5b9f53a95/tbb-v2022.0.0/src/tbb/task_dispatcher.h:334
    #8 0x1553a516e609 in tbb::detail::d1::task* tbb::detail::r1::task_dispatcher::local_wait_for_all<tbb::detail::r1::outermost_worker_waiter>(tbb::detail::d1::task*, tbb::detail::r1::outermost_worker_waiter&) /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc12/external/tbb/v2022.0.0-79b5a917b0c13f831cd534a5b9f53a95/tbb-v2022.0.0/src/tbb/task_dispatcher.h:470
    #9 0x1553a516e609 in tbb::detail::r1::arena::process(tbb::detail::r1::thread_data&) /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc12/external/tbb/v2022.0.0-79b5a917b0c13f831cd534a5b9f53a95/tbb-v2022.0.0/src/tbb/arena.cpp:215
    #10 0x1553a516e609 in tbb::detail::r1::thread_dispatcher_client::process(tbb::detail::r1::thread_data&) /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc12/external/tbb/v2022.0.0-79b5a917b0c13f831cd534a5b9f53a95/tbb-v2022.0.0/src/tbb/thread_dispatcher_client.h:41
    #11 0x1553a516e609 in tbb::detail::r1::thread_dispatcher::process(rml::job&) /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc12/external/tbb/v2022.0.0-79b5a917b0c13f831cd534a5b9f53a95/tbb-v2022.0.0/src/tbb/thread_dispatcher.cpp:195
    #12 0x1553a51666b7 in tbb::detail::r1::rml::private_worker::run() /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc12/external/tbb/v2022.0.0-79b5a917b0c13f831cd534a5b9f53a95/tbb-v2022.0.0/src/tbb/private_server.cpp:271
    #13 0x1553a51666b7 in tbb::detail::r1::rml::private_worker::thread_routine(void*) /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc12/external/tbb/v2022.0.0-79b5a917b0c13f831cd534a5b9f53a95/tbb-v2022.0.0/src/tbb/private_server.cpp:221
    #14 0x1553a3e051c9 in start_thread (/lib64/libpthread.so.0+0x81c9)
    #15 0x1553a44628d2 in clone (/lib64/libc.so.6+0x398d2)

Address 0x155346464390 is located in stack of thread T3 at offset 55856 in frame
    #0 0x1552db0fc80f in Phase2L1CaloPFClusterEmulator::produce(edm::Event&, edm::EventSetup const&) (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02897/el8_amd64_gcc12/cms/cmssw/CMSSW_15_1_ASAN_X_2025-07-07-2300/lib/el8_amd64_gcc12/pluginL1TriggerL1CaloTriggerAuto.so+0x4fc80f)

  This frame has 154 object(s):
    [32, 33) '<unknown>'
    [48, 49) '__a'
    [64, 65) '__a2'
    [80, 81) '__a'
    [96, 97) '__a2'
    [112, 113) '__a'
    [128, 129) '__a2'
    [144, 148) '<unknown>'
    [160, 164) 'resolverIndex'
    [176, 180) '<unknown>'
    [192, 196) '<unknown>'
    [208, 216) 'pfclusterCands' (line 86)
    [240, 248) '__for_begin' (line 96)
    [272, 280) '__for_end' (line 96)
    [304, 312) '__for_begin' (line 211)
    [336, 344) '__for_end' (line 211)
    [368, 376) '<unknown>'
    [400, 408) '<unknown>'
    [432, 440) '<unknown>'
    [464, 472) '<unknown>'
    [496, 504) '<unknown>'
    [528, 536) '<unknown>'
    [560, 568) '<unknown>'
    [592, 600) '<unknown>'
    [624, 632) '<unknown>'
    [656, 664) 'desc'
    [688, 696) '<unknown>'
    [720, 728) 'dataKey'
    [752, 760) '<unknown>'
    [784, 792) '<unknown>'
    [816, 824) '<unknown>'
    [848, 856) '<unknown>'
    [880, 888) '__guard'
    [912, 920) 'typeID'
    [944, 952) '<unknown>'
    [976, 984) '<unknown>'
    [1008, 1020) 'pfclusterReturn'
    [1040, 1052) 'et_sumEta'
    [1072, 1084) 'max'
    [1104, 1116) 'best12'
    [1136, 1148) 'best34'
    [1168, 1180) 'best56'
    [1200, 1212) 'best1234'
    [1232, 1244) 'bestAll'
    [1264, 1276) 'x'
    [1296, 1308) 'x'
    [1328, 1340) 'x'
    [1360, 1372) 'x'
    [1392, 1404) 'x'
    [1424, 1436) 'pfclusterReturn'
    [1456, 1468) 'et_sumEta'
    [1488, 1500) 'max'
    [1520, 1532) 'best01'
    [1552, 1564) 'best23'
    [1584, 1596) 'best45'
    [1616, 1628) 'best67'
    [1648, 1660) 'best89'
    [1680, 1692) 'best1011'
    [1712, 1724) 'best0123'
    [1744, 1756) 'best4567'
    [1776, 1788) 'best891011'
    [1808, 1820) 'best01234567'
    [1840, 1852) 'bestAll'
    [1872, 1884) 'x'
    [1904, 1916) 'x'
    [1936, 1948) 'x'
    [1968, 1980) 'x'
    [2000, 2012) 'x'
    [2032, 2044) 'x'
    [2064, 2076) 'x'
    [2096, 2108) 'x'
    [2128, 2140) 'x'
    [2160, 2172) 'x'
    [2192, 2204) 'x'
    [2224, 2240) '<unknown>'
    [2256, 2272) '<unknown>'
    [2288, 2304) '<unknown>'
    [2320, 2336) '<unknown>'
    [2352, 2368) '<unknown>'
    [2384, 2400) 'typeTag'
    [2416, 2432) '<unknown>'
    [2448, 2464) '<unknown>'
    [2480, 2496) '<unknown>'
    [2512, 2528) '<unknown>'
    [2544, 2560) 'typeTag'
    [2576, 2592) '<unknown>'
    [2608, 2624) '<unknown>'
    [2640, 2656) 'whyFailedFactory'
    [2672, 2688) '<unknown>'
    [2704, 2720) '<unknown>'
    [2736, 2752) '<unknown>'
    [2768, 2784) '<unknown>'
    [2800, 2816) '<unknown>'
    [2832, 2848) 'typeTag'
    [2864, 2880) '<unknown>'
    [2896, 2912) '<unknown>'
    [2928, 2944) 'key'
    [2960, 2976) '<unknown>'
    [2992, 3008) '<unknown>'
    [3024, 3040) 'typeTag'
    [3056, 3072) '<unknown>'
    [3088, 3104) '<unknown>'
    [3120, 3136) '<unknown>'
    [3152, 3168) '__guard'
    [3184, 3200) 'key'
    [3216, 3232) '<unknown>'
    [3248, 3264) '<unknown>'
    [3280, 3296) 'typeTag'
    [3312, 3328) '<unknown>'
    [3344, 3360) '<unknown>'
    [3376, 3392) '<unknown>'
    [3408, 3424) '__guard'
    [3440, 3456) 'key'
    [3472, 3488) '<unknown>'
    [3504, 3520) '<unknown>'
    [3536, 3552) 'typeTag'
    [3568, 3584) '<unknown>'
    [3600, 3616) '<unknown>'
    [3632, 3648) '<unknown>'
    [3664, 3680) '__guard'
    [3696, 3720) '<unknown>'
    [3760, 3792) 'caloTowerCollection' (line 88)
    [3824, 3856) 'hfHandle' (line 175)
    [3888, 3920) '<unknown>'
    [3952, 3984) 'bh'
    [4016, 4048) '<unknown>'
    [4080, 4112) '<unknown>'
    [4144, 4176) '<unknown>'
    [4208, 4240) '<unknown>'
    [4272, 4320) '<unknown>'
    [4352, 4448) 'tempPfclusters' (line 157)
    [4480, 4576) 'tempPfclustersHF' (line 281)
    [4608, 4704) 'pfcluster'
    [4736, 4832) 'pfcluster'
    [4864, 5016) 'l1CaloPFCluster' (line 165)
    [5088, 5240) 'l1CaloPFCluster' (line 289)
    [5312, 5540) 'etaPeak'
    [5616, 5904) 'etaPeak'
    [5968, 6472) '<unknown>'
    [6544, 7216) 'temporary' (line 139)
    [7344, 8496) 'temporaryHF' (line 264)
    [8624, 10080) 'tempX'
    [10208, 12224) 'region'
    [12352, 14368) 'r'
    [14496, 17952) 'region'
    [18080, 21536) 'r'
    [21664, 28576) 'hfEta' (line 181)
    [28832, 35744) 'hfPhi' (line 182)
    [36000, 45792) 'GCTintTowers' (line 93)
    [46048, 55840) 'realEta' (line 94) <== Memory access at offset 55856 overflows this variable
    [56096, 65888) 'realPhi' (line 95)
    [66144, 79968) 'hfTowers' (line 180)
    [80224, 94048) 'regionsHF' (line 197)
    [94304, 118496) 'regions' (line 104)
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
Thread T3 created by T0 here:
    #0 0x1553a644a136 in __interceptor_pthread_create ../../../../libsanitizer/asan/asan_interceptors.cpp:207
    #1 0x1553a51655ff in tbb::detail::r1::rml::internal::thread_monitor::launch(void* (*)(void*), void*, unsigned long) /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc12/external/tbb/v2022.0.0-79b5a917b0c13f831cd534a5b9f53a95/tbb-v2022.0.0/src/tbb/rml_thread_monitor.h:208
    #2 0x1553a51655ff in tbb::detail::r1::rml::private_worker::wake_or_launch() /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc12/external/tbb/v2022.0.0-79b5a917b0c13f831cd534a5b9f53a95/tbb-v2022.0.0/src/tbb/private_server.cpp:305
    #3 0x1553a51655ff in tbb::detail::r1::rml::private_server::wake_some(int) /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc12/external/tbb/v2022.0.0-79b5a917b0c13f831cd534a5b9f53a95/tbb-v2022.0.0/src/tbb/private_server.cpp:412

SUMMARY: AddressSanitizer: stack-buffer-overflow (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02897/el8_amd64_gcc12/cms/cmssw/CMSSW_15_1_ASAN_X_2025-07-07-2300/lib/el8_amd64_gcc12/pluginL1TriggerL1CaloTriggerAuto.so+0x51558b) in Phase2L1CaloPFClusterEmulator::produce(edm::Event&, edm::EventSetup const&)
Shadow bytes around the buggy address:
  0x02aae8c84820: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x02aae8c84830: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x02aae8c84840: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x02aae8c84850: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x02aae8c84860: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x02aae8c84870: f2 f2[f2]f2 f2 f2 f2 f2 f2 f2 f2 f2 f2 f2 f2 f2
  0x02aae8c84880: f2 f2 f2 f2 f2 f2 f2 f2 f2 f2 f2 f2 f2 f2 f2 f2
  0x02aae8c84890: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x02aae8c848a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x02aae8c848b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x02aae8c848c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==992550==ABORTING
```

[Full Logs](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_15_1_ASAN_X_2025-07-07-2300/pyRelValMatrixLogs/run/23634.0_TTbar_14TeV+Run4D95/step2_TTbar_14TeV+Run4D95.log#/)

**Comment by iarspider** [comment]
@akritkbehera this should be fixed by https://github.com/cms-sw/cmssw/pull/48478, which was merged only 10 minutes ago and was not part of CMSSW_15_1_ASAN_X_2025-07-07-2300

**Comment by akritkbehera** [comment]
Post [#48478](https://github.com/cms-sw/cmssw/pull/48478)
The RelVals are still failing with the same error on CMSSW_15_1_ASAN_X_2025-07-11-2300

**Comment by akritkbehera** [comment]
Mentioned in [#48368](https://github.com/cms-sw/cmssw/issues/48368)
