### ISSUE TITLE
RelVals 138.1, 138.2 are failing on Multiple IBs

### ISSUE THREAD

**Issue by akritkbehera** [cms-sw/cmssw#48724]
Hello,

The relavals `138.1`, `138.2` are failing with ```BASHobject of class vector<reco::DeDxData> read too many bytes: 24 instead of 20```

ERROR

```BASH
----- Begin Fatal Exception 12-Aug-2025 05:49:34 CEST-----------------------
An exception of category 'FileReadError' occurred while
   [0] Processing  Event run: 343498 lumi: 775 event: 12655182 stream: 1
   [1] Running path 'RECOoutput_step'
   [2] Prefetching for module PoolOutputModule/'RECOoutput'
   [3] While reading from source edm::ValueMap<reco::DeDxData> dedxHarmonic2CosmicTF '' RECO
   [4] Reading branch recoDeDxDataedmValueMap_dedxHarmonic2CosmicTF__RECO.
   Additional Info:
      [a] Fatal Root Error: @SUB=TBufferFile::CheckByteCount
object of class vector<reco::DeDxData> read too many bytes: 24 instead of 20

----- End Fatal Exception -------------------------------------------------
```

Full Logs [here](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_15_1_X_2025-08-11-2300/pyRelValMatrixLogs/run/138.1_PromptCosmics2021/step2_PromptCosmics2021.log#/439-439)

**Comment by akritkbehera** [comment]
Should be resolved with [#48697](https://github.com/cms-sw/cmssw/pull/48697)

**Comment by stahlleiton** [comment]
Do the errors still persist in the latest IBs (after August 13th 11:00 am)?

If not, the would be great to close this issue

**Comment by akritkbehera** [comment]
The errors appear to be resolved in IBs CMSSW_15_1_X, CMSSW_15_1_NONLTO_X, and CMSSW_15_1_MULTIARCHS. Looks like the issue is fixed. Will close once the remaining IBs are also done.
