### ISSUE TITLE
[RNTUPLE_X] RelVal 1046.0 failed: Missing StreamerInfo?

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#49365]
In CMSSW_16_0_RNTUPLE_X_2025-11-10-2300, RelVal 1046.0 failed with SIGSEGV:

```
Thread 1 (Thread 0x151ac2513580 (LWP 3022096) "cmsRun"):
#0  0x0000151ac3b86bb1 in poll () from /lib64/libc.so.6
#1  0x0000151abed3d88e in edm::service::InitRootHandlers::stacktraceFromThread() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02915/el8_amd64_gcc13/cms/cmssw/CMSSW_16_0_RNTUPLE_X_2025-11-10-2300/lib/el8_amd64_gcc13/pluginFWCoreServicesPlugins.so
#2  0x0000151abed3da93 in sig_dostack_then_abort () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02915/el8_amd64_gcc13/cms/cmssw/CMSSW_16_0_RNTUPLE_X_2025-11-10-2300/lib/el8_amd64_gcc13/pluginFWCoreServicesPlugins.so
#3  <signal handler called>
#4  0x0000151a8947e090 in PPSDiamondSampicTimingCalibrationPCLHarvester::calibDb(dqm::implementation::IGetter&) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02915/el8_amd64_gcc13/cms/cmssw/CMSSW_16_0_RNTUPLE_X_2025-11-10-2300/lib/el8_amd64_gcc13/pluginCalibPPSTimingCalibrationPlugins.so
#5  0x0000151a89475cc5 in non-virtual thunk to DQMEDHarvester::endProcessBlockProduce(edm::ProcessBlock&) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02915/el8_amd64_gcc13/cms/cmssw/CMSSW_16_0_RNTUPLE_X_2025-11-10-2300/lib/el8_amd64_gcc13/pluginCalibPPSTimingCalibrationPlugins.so
#6  0x0000151ac494e9c0 in edm::one::EDProducerBase::doEndProcessBlock(edm::ProcessBlockPrincipal const&, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02915/el8_amd64_gcc13/cms/cmssw/CMSSW_16_0_RNTUPLE_X_2025-11-10-2300/lib/el8_amd64_gcc13/libFWCoreFramework.so
#7  0x0000151ac493cc60 in edm::WorkerT<edm::one::EDProducerBase>::implDoEndProcessBlock(edm::ProcessBlockPrincipal const&, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02915/el8_amd64_gcc13/cms/cmssw/CMSSW_16_0_RNTUPLE_X_2025-11-10-2300/lib/el8_amd64_gcc13/libFWCoreFramework.so
#8  0x0000151ac4888525 in std::__exception_ptr::exception_ptr edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::ProcessBlockPrincipal, (edm::BranchActionType)3> >(std::__exception_ptr::exception_ptr, edm::OccurrenceTraits<edm::ProcessBlockPrincipal, (edm::BranchActionType)3>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::ProcessBlockPrincipal, (edm::BranchActionType)3>::Context const*) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02915/el8_amd64_gcc13/cms/cmssw/CMSSW_16_0_RNTUPLE_X_2025-11-10-2300/lib/el8_amd64_gcc13/libFWCoreFramework.so
#9  0x0000151ac4888854 in edm::SerialTaskQueue::QueuedTask<edm::SerialTaskQueueChain::push<edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::ProcessBlockPrincipal, (edm::BranchActionType)3> >::execute()::{lambda()#1}&>(tbb::detail::d2::task_group&, edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::ProcessBlockPrincipal, (edm::BranchActionType)3> >::execute()::{lambda()#1}&)::{lambda()#1}>::execute() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02915/el8_amd64_gcc13/cms/cmssw/CMSSW_16_0_RNTUPLE_X_2025-11-10-2300/lib/el8_amd64_gcc13/libFWCoreFramework.so
#10 0x0000151ac4b30417 in tbb::detail::d2::function_task<edm::SerialTaskQueue::spawn(edm::SerialTaskQueue::TaskBase&)::{lambda()#1}>::execute(tbb::detail::d1::execution_data&) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02915/el8_amd64_gcc13/cms/cmssw/CMSSW_16_0_RNTUPLE_X_2025-11-10-2300/lib/el8_amd64_gcc13/libFWCoreConcurrency.so
#11 0x0000151ac40af2f3 in tbb::detail::r1::task_dispatcher::local_wait_for_all<false, tbb::detail::r1::external_waiter> (waiter=..., t=0x151ac1fdac00, this=<optimized out>) at src/tbb/task_dispatcher.h:344
#12 tbb::detail::r1::task_dispatcher::local_wait_for_all<tbb::detail::r1::external_waiter> (waiter=..., t=<optimized out>, this=<optimized out>) at src/tbb/task_dispatcher.h:487
#13 tbb::detail::r1::task_dispatcher::execute_and_wait (t=<optimized out>, wait_ctx=..., w_ctx=...) at src/tbb/task_dispatcher.cpp:169
#14 0x0000151ac4844e5f in edm::FinalWaitingTask::wait() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02915/el8_amd64_gcc13/cms/cmssw/CMSSW_16_0_RNTUPLE_X_2025-11-10-2300/lib/el8_amd64_gcc13/libFWCoreFramework.so
#15 0x0000151ac4859b55 in edm::EventProcessor::endProcessBlock(bool, bool) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02915/el8_amd64_gcc13/cms/cmssw/CMSSW_16_0_RNTUPLE_X_2025-11-10-2300/lib/el8_amd64_gcc13/libFWCoreFramework.so
#16 0x0000151ac47f25ff in edm::EventProcessor::runToCompletion() [clone .cold] () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02915/el8_amd64_gcc13/cms/cmssw/CMSSW_16_0_RNTUPLE_X_2025-11-10-2300/lib/el8_amd64_gcc13/libFWCoreFramework.so
#17 0x000000000040916d in tbb::detail::d1::task_arena_function<main::{lambda()#1}::operator()() const::{lambda()#1}, void>::operator()() const ()
#18 0x0000151ac409e8c2 in tbb::detail::r1::task_arena_impl::execute (ta=..., d=...) at src/tbb/arena.cpp:860
#19 0x000000000040abfe in main::{lambda()#1}::operator()() const ()
#20 0x0000000000405268 in main ()
```

The crash is preceeded by the following exception:

```
----- Begin Fatal Exception 11-Nov-2025 03:39:15 CET-----------------------
An exception of category 'FileReadError' occurred while
   [0] Calling InputSource::readRun_
   [1] Reading branch llMEtoEDM_MEtoEDMConvertPPSDiamondSampicTimingCalib_MEtoEDMConverterRun_ALCA
   Additional Info:
      [a] Fatal Root Error: @SUB=TBufferFile::ReadVersion
Could not find the StreamerInfo with a checksum of 0x27387d20 for the class "MEtoEDM<long>::MEtoEDMObject" (buffer with no parent)

----- End Fatal Exception -------------------------------------------------
```

**Comment by Dr15Jones** [comment]
Assign root

**Comment by Dr15Jones** [comment]
Assign core

**Comment by Dr15Jones** [comment]
From the branch name, the type should be `MEtoEDM<long long>::MEtoEDMObject`

**Comment by iarspider** [comment]
Could it be related to https://github.com/cms-sw/cmssw/issues/49298?

**Comment by Dr15Jones** [comment]
> Could it be related to https://github.com/cms-sw/cmssw/issues/49298?

Most likely.

**Comment by makortel** [comment]
type root

**Comment by makortel** [comment]
Given that ROOT already addressed https://github.com/root-project/root/issues/20282 with https://github.com/root-project/root/pull/20322, I don't think it is worth of us doing anything but asking it to be backported to ROOT 6.36 and updating RNTUPLE_X to use that.

**Comment by makortel** [comment]
@pcanal @vepadulano @jblomer just FYI that the workaround of allowing `MEtoEDM<long>` we tried in https://github.com/cms-sw/cmssw/pull/49299 was not sufficient. I'm hoping https://github.com/root-project/root/pull/20322 would fix the problem of this issue (and we could then remove the attempted workaround), but we'd need https://github.com/root-project/root/pull/20322 to be backported to ROOT 6.36

**Comment by jblomer** [comment]
@makortel Noted, I reopened our issue

**Comment by makortel** [comment]
Thanks!

**Comment by makortel** [comment]
@smuzaffar The backport of https://github.com/root-project/root/issues/20282 was merged in ROOT's `v6-36-00-patches` (via https://github.com/root-project/root/pull/20420). Could we update ROOT in our ROOT636_X and RNTUPLE_X branches to the head of `v6-36-00-patches`?

(or at least in RNTUPLE_X if you'd have any concerns in updating ROOT636_X given the plan to make ROOT636_X the default early next week?)

**Comment by smuzaffar** [comment]
done: https://github.com/cms-sw/cmsdist/pull/10196 and https://github.com/cms-sw/cmsdist/pull/10195

**Comment by makortel** [comment]
Thanks!

**Comment by makortel** [comment]
> [cms-sw/cmsdist#10196](https://github.com/cms-sw/cmsdist/pull/10196)

This PR was part of CMSSW_16_0_RNTUPLE_X_2025-11-18-2300. Step 4 of 1046.0 still failed with
```
----- Begin Fatal Exception 19-Nov-2025 03:12:50 CET-----------------------
An exception of category 'FileReadError' occurred while
   [0] Calling InputSource::readRun_
   [1] Reading branch llMEtoEDM_MEtoEDMConvertPPSDiamondSampicTimingCalib_MEtoEDMConverterRun_ALCA
   Additional Info:
      [a] Fatal Root Error: @SUB=TBufferFile::ReadVersion
Could not find the StreamerInfo with a checksum of 0x27387d20 for the class "MEtoEDM<long>::MEtoEDMObject" (buffer with no parent)

----- End Fatal Exception -------------------------------------------------
```
I guess we need to take a deeper look

**Comment by jblomer** [comment]
I can reproduce this. It only appears with an inner class (`MEtoEDMObject`). I'm actually surprised that we do not see this without the inner class. I need to think for a moment about this.

**Comment by makortel** [comment]
This workflow seems to be working now

**Comment by makortel** [comment]
+core
